// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.

package switchboard_v2

import (
	"errors"
	ag_binary "github.com/gagliardetto/binary"
	ag_solanago "github.com/gagliardetto/solana-go"
	ag_format "github.com/gagliardetto/solana-go/text/format"
	ag_treeout "github.com/gagliardetto/treeout"
)

// AggregatorFunctionUpsert is the `aggregatorFunctionUpsert` instruction.
type AggregatorFunctionUpsert struct {
	Params *AggregatorFunctionUpsertParams

	// [0] = [WRITE] aggregator
	//
	// [1] = [] function
	//
	// [2] = [SIGNER] functionEnclaveSigner
	//
	// [3] = [] verifier
	//
	// [4] = [WRITE, SIGNER] payer
	//
	// [5] = [] systemProgram
	ag_solanago.AccountMetaSlice `bin:"-"`
}

// NewAggregatorFunctionUpsertInstructionBuilder creates a new `AggregatorFunctionUpsert` instruction builder.
func NewAggregatorFunctionUpsertInstructionBuilder() *AggregatorFunctionUpsert {
	nd := &AggregatorFunctionUpsert{
		AccountMetaSlice: make(ag_solanago.AccountMetaSlice, 6),
	}
	return nd
}

// SetParams sets the "params" parameter.
func (inst *AggregatorFunctionUpsert) SetParams(params AggregatorFunctionUpsertParams) *AggregatorFunctionUpsert {
	inst.Params = &params
	return inst
}

// SetAggregatorAccount sets the "aggregator" account.
func (inst *AggregatorFunctionUpsert) SetAggregatorAccount(aggregator ag_solanago.PublicKey) *AggregatorFunctionUpsert {
	inst.AccountMetaSlice[0] = ag_solanago.Meta(aggregator).WRITE()
	return inst
}

// GetAggregatorAccount gets the "aggregator" account.
func (inst *AggregatorFunctionUpsert) GetAggregatorAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(0)
}

// SetFunctionAccount sets the "function" account.
func (inst *AggregatorFunctionUpsert) SetFunctionAccount(function ag_solanago.PublicKey) *AggregatorFunctionUpsert {
	inst.AccountMetaSlice[1] = ag_solanago.Meta(function)
	return inst
}

// GetFunctionAccount gets the "function" account.
func (inst *AggregatorFunctionUpsert) GetFunctionAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(1)
}

// SetFunctionEnclaveSignerAccount sets the "functionEnclaveSigner" account.
func (inst *AggregatorFunctionUpsert) SetFunctionEnclaveSignerAccount(functionEnclaveSigner ag_solanago.PublicKey) *AggregatorFunctionUpsert {
	inst.AccountMetaSlice[2] = ag_solanago.Meta(functionEnclaveSigner).SIGNER()
	return inst
}

// GetFunctionEnclaveSignerAccount gets the "functionEnclaveSigner" account.
func (inst *AggregatorFunctionUpsert) GetFunctionEnclaveSignerAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(2)
}

// SetVerifierAccount sets the "verifier" account.
func (inst *AggregatorFunctionUpsert) SetVerifierAccount(verifier ag_solanago.PublicKey) *AggregatorFunctionUpsert {
	inst.AccountMetaSlice[3] = ag_solanago.Meta(verifier)
	return inst
}

// GetVerifierAccount gets the "verifier" account.
func (inst *AggregatorFunctionUpsert) GetVerifierAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(3)
}

// SetPayerAccount sets the "payer" account.
func (inst *AggregatorFunctionUpsert) SetPayerAccount(payer ag_solanago.PublicKey) *AggregatorFunctionUpsert {
	inst.AccountMetaSlice[4] = ag_solanago.Meta(payer).WRITE().SIGNER()
	return inst
}

// GetPayerAccount gets the "payer" account.
func (inst *AggregatorFunctionUpsert) GetPayerAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(4)
}

// SetSystemProgramAccount sets the "systemProgram" account.
func (inst *AggregatorFunctionUpsert) SetSystemProgramAccount(systemProgram ag_solanago.PublicKey) *AggregatorFunctionUpsert {
	inst.AccountMetaSlice[5] = ag_solanago.Meta(systemProgram)
	return inst
}

// GetSystemProgramAccount gets the "systemProgram" account.
func (inst *AggregatorFunctionUpsert) GetSystemProgramAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(5)
}

func (inst AggregatorFunctionUpsert) Build() *Instruction {
	return &Instruction{BaseVariant: ag_binary.BaseVariant{
		Impl:   inst,
		TypeID: Instruction_AggregatorFunctionUpsert,
	}}
}

// ValidateAndBuild validates the instruction parameters and accounts;
// if there is a validation error, it returns the error.
// Otherwise, it builds and returns the instruction.
func (inst AggregatorFunctionUpsert) ValidateAndBuild() (*Instruction, error) {
	if err := inst.Validate(); err != nil {
		return nil, err
	}
	return inst.Build(), nil
}

func (inst *AggregatorFunctionUpsert) Validate() error {
	// Check whether all (required) parameters are set:
	{
		if inst.Params == nil {
			return errors.New("Params parameter is not set")
		}
	}

	// Check whether all (required) accounts are set:
	{
		if inst.AccountMetaSlice[0] == nil {
			return errors.New("accounts.Aggregator is not set")
		}
		if inst.AccountMetaSlice[1] == nil {
			return errors.New("accounts.Function is not set")
		}
		if inst.AccountMetaSlice[2] == nil {
			return errors.New("accounts.FunctionEnclaveSigner is not set")
		}
		if inst.AccountMetaSlice[3] == nil {
			return errors.New("accounts.Verifier is not set")
		}
		if inst.AccountMetaSlice[4] == nil {
			return errors.New("accounts.Payer is not set")
		}
		if inst.AccountMetaSlice[5] == nil {
			return errors.New("accounts.SystemProgram is not set")
		}
	}
	return nil
}

func (inst *AggregatorFunctionUpsert) EncodeToTree(parent ag_treeout.Branches) {
	parent.Child(ag_format.Program(ProgramName, ProgramID)).
		//
		ParentFunc(func(programBranch ag_treeout.Branches) {
			programBranch.Child(ag_format.Instruction("AggregatorFunctionUpsert")).
				//
				ParentFunc(func(instructionBranch ag_treeout.Branches) {

					// Parameters of the instruction:
					instructionBranch.Child("Params[len=1]").ParentFunc(func(paramsBranch ag_treeout.Branches) {
						paramsBranch.Child(ag_format.Param("Params", *inst.Params))
					})

					// Accounts of the instruction:
					instructionBranch.Child("Accounts[len=6]").ParentFunc(func(accountsBranch ag_treeout.Branches) {
						accountsBranch.Child(ag_format.Meta("           aggregator", inst.AccountMetaSlice.Get(0)))
						accountsBranch.Child(ag_format.Meta("             function", inst.AccountMetaSlice.Get(1)))
						accountsBranch.Child(ag_format.Meta("functionEnclaveSigner", inst.AccountMetaSlice.Get(2)))
						accountsBranch.Child(ag_format.Meta("             verifier", inst.AccountMetaSlice.Get(3)))
						accountsBranch.Child(ag_format.Meta("                payer", inst.AccountMetaSlice.Get(4)))
						accountsBranch.Child(ag_format.Meta("        systemProgram", inst.AccountMetaSlice.Get(5)))
					})
				})
		})
}

func (obj AggregatorFunctionUpsert) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	// Serialize `Params` param:
	err = encoder.Encode(obj.Params)
	if err != nil {
		return err
	}
	return nil
}
func (obj *AggregatorFunctionUpsert) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	// Deserialize `Params`:
	err = decoder.Decode(&obj.Params)
	if err != nil {
		return err
	}
	return nil
}

// NewAggregatorFunctionUpsertInstruction declares a new AggregatorFunctionUpsert instruction with the provided parameters and accounts.
func NewAggregatorFunctionUpsertInstruction(
	// Parameters:
	params AggregatorFunctionUpsertParams,
	// Accounts:
	aggregator ag_solanago.PublicKey,
	function ag_solanago.PublicKey,
	functionEnclaveSigner ag_solanago.PublicKey,
	verifier ag_solanago.PublicKey,
	payer ag_solanago.PublicKey,
	systemProgram ag_solanago.PublicKey) *AggregatorFunctionUpsert {
	return NewAggregatorFunctionUpsertInstructionBuilder().
		SetParams(params).
		SetAggregatorAccount(aggregator).
		SetFunctionAccount(function).
		SetFunctionEnclaveSignerAccount(functionEnclaveSigner).
		SetVerifierAccount(verifier).
		SetPayerAccount(payer).
		SetSystemProgramAccount(systemProgram)
}
