// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.

package switchboard_v2

import (
	"errors"
	ag_binary "github.com/gagliardetto/binary"
	ag_solanago "github.com/gagliardetto/solana-go"
	ag_format "github.com/gagliardetto/solana-go/text/format"
	ag_treeout "github.com/gagliardetto/treeout"
)

// AggregatorOpenRound is the `aggregatorOpenRound` instruction.
type AggregatorOpenRound struct {
	Params *AggregatorOpenRoundParams

	// [0] = [WRITE] aggregator
	//
	// [1] = [WRITE] lease
	//
	// [2] = [WRITE] oracleQueue
	//
	// [3] = [] queueAuthority
	//
	// [4] = [WRITE] permission
	//
	// [5] = [WRITE] escrow
	//
	// [6] = [] programState
	//
	// [7] = [WRITE] payoutWallet
	//
	// [8] = [] tokenProgram
	//
	// [9] = [] dataBuffer
	//
	// [10] = [] mint
	ag_solanago.AccountMetaSlice `bin:"-"`
}

// NewAggregatorOpenRoundInstructionBuilder creates a new `AggregatorOpenRound` instruction builder.
func NewAggregatorOpenRoundInstructionBuilder() *AggregatorOpenRound {
	nd := &AggregatorOpenRound{
		AccountMetaSlice: make(ag_solanago.AccountMetaSlice, 11),
	}
	return nd
}

// SetParams sets the "params" parameter.
func (inst *AggregatorOpenRound) SetParams(params AggregatorOpenRoundParams) *AggregatorOpenRound {
	inst.Params = &params
	return inst
}

// SetAggregatorAccount sets the "aggregator" account.
func (inst *AggregatorOpenRound) SetAggregatorAccount(aggregator ag_solanago.PublicKey) *AggregatorOpenRound {
	inst.AccountMetaSlice[0] = ag_solanago.Meta(aggregator).WRITE()
	return inst
}

// GetAggregatorAccount gets the "aggregator" account.
func (inst *AggregatorOpenRound) GetAggregatorAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(0)
}

// SetLeaseAccount sets the "lease" account.
func (inst *AggregatorOpenRound) SetLeaseAccount(lease ag_solanago.PublicKey) *AggregatorOpenRound {
	inst.AccountMetaSlice[1] = ag_solanago.Meta(lease).WRITE()
	return inst
}

// GetLeaseAccount gets the "lease" account.
func (inst *AggregatorOpenRound) GetLeaseAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(1)
}

// SetOracleQueueAccount sets the "oracleQueue" account.
func (inst *AggregatorOpenRound) SetOracleQueueAccount(oracleQueue ag_solanago.PublicKey) *AggregatorOpenRound {
	inst.AccountMetaSlice[2] = ag_solanago.Meta(oracleQueue).WRITE()
	return inst
}

// GetOracleQueueAccount gets the "oracleQueue" account.
func (inst *AggregatorOpenRound) GetOracleQueueAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(2)
}

// SetQueueAuthorityAccount sets the "queueAuthority" account.
func (inst *AggregatorOpenRound) SetQueueAuthorityAccount(queueAuthority ag_solanago.PublicKey) *AggregatorOpenRound {
	inst.AccountMetaSlice[3] = ag_solanago.Meta(queueAuthority)
	return inst
}

// GetQueueAuthorityAccount gets the "queueAuthority" account.
func (inst *AggregatorOpenRound) GetQueueAuthorityAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(3)
}

// SetPermissionAccount sets the "permission" account.
func (inst *AggregatorOpenRound) SetPermissionAccount(permission ag_solanago.PublicKey) *AggregatorOpenRound {
	inst.AccountMetaSlice[4] = ag_solanago.Meta(permission).WRITE()
	return inst
}

// GetPermissionAccount gets the "permission" account.
func (inst *AggregatorOpenRound) GetPermissionAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(4)
}

// SetEscrowAccount sets the "escrow" account.
func (inst *AggregatorOpenRound) SetEscrowAccount(escrow ag_solanago.PublicKey) *AggregatorOpenRound {
	inst.AccountMetaSlice[5] = ag_solanago.Meta(escrow).WRITE()
	return inst
}

// GetEscrowAccount gets the "escrow" account.
func (inst *AggregatorOpenRound) GetEscrowAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(5)
}

// SetProgramStateAccount sets the "programState" account.
func (inst *AggregatorOpenRound) SetProgramStateAccount(programState ag_solanago.PublicKey) *AggregatorOpenRound {
	inst.AccountMetaSlice[6] = ag_solanago.Meta(programState)
	return inst
}

// GetProgramStateAccount gets the "programState" account.
func (inst *AggregatorOpenRound) GetProgramStateAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(6)
}

// SetPayoutWalletAccount sets the "payoutWallet" account.
func (inst *AggregatorOpenRound) SetPayoutWalletAccount(payoutWallet ag_solanago.PublicKey) *AggregatorOpenRound {
	inst.AccountMetaSlice[7] = ag_solanago.Meta(payoutWallet).WRITE()
	return inst
}

// GetPayoutWalletAccount gets the "payoutWallet" account.
func (inst *AggregatorOpenRound) GetPayoutWalletAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(7)
}

// SetTokenProgramAccount sets the "tokenProgram" account.
func (inst *AggregatorOpenRound) SetTokenProgramAccount(tokenProgram ag_solanago.PublicKey) *AggregatorOpenRound {
	inst.AccountMetaSlice[8] = ag_solanago.Meta(tokenProgram)
	return inst
}

// GetTokenProgramAccount gets the "tokenProgram" account.
func (inst *AggregatorOpenRound) GetTokenProgramAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(8)
}

// SetDataBufferAccount sets the "dataBuffer" account.
func (inst *AggregatorOpenRound) SetDataBufferAccount(dataBuffer ag_solanago.PublicKey) *AggregatorOpenRound {
	inst.AccountMetaSlice[9] = ag_solanago.Meta(dataBuffer)
	return inst
}

// GetDataBufferAccount gets the "dataBuffer" account.
func (inst *AggregatorOpenRound) GetDataBufferAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(9)
}

// SetMintAccount sets the "mint" account.
func (inst *AggregatorOpenRound) SetMintAccount(mint ag_solanago.PublicKey) *AggregatorOpenRound {
	inst.AccountMetaSlice[10] = ag_solanago.Meta(mint)
	return inst
}

// GetMintAccount gets the "mint" account.
func (inst *AggregatorOpenRound) GetMintAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(10)
}

func (inst AggregatorOpenRound) Build() *Instruction {
	return &Instruction{BaseVariant: ag_binary.BaseVariant{
		Impl:   inst,
		TypeID: Instruction_AggregatorOpenRound,
	}}
}

// ValidateAndBuild validates the instruction parameters and accounts;
// if there is a validation error, it returns the error.
// Otherwise, it builds and returns the instruction.
func (inst AggregatorOpenRound) ValidateAndBuild() (*Instruction, error) {
	if err := inst.Validate(); err != nil {
		return nil, err
	}
	return inst.Build(), nil
}

func (inst *AggregatorOpenRound) Validate() error {
	// Check whether all (required) parameters are set:
	{
		if inst.Params == nil {
			return errors.New("Params parameter is not set")
		}
	}

	// Check whether all (required) accounts are set:
	{
		if inst.AccountMetaSlice[0] == nil {
			return errors.New("accounts.Aggregator is not set")
		}
		if inst.AccountMetaSlice[1] == nil {
			return errors.New("accounts.Lease is not set")
		}
		if inst.AccountMetaSlice[2] == nil {
			return errors.New("accounts.OracleQueue is not set")
		}
		if inst.AccountMetaSlice[3] == nil {
			return errors.New("accounts.QueueAuthority is not set")
		}
		if inst.AccountMetaSlice[4] == nil {
			return errors.New("accounts.Permission is not set")
		}
		if inst.AccountMetaSlice[5] == nil {
			return errors.New("accounts.Escrow is not set")
		}
		if inst.AccountMetaSlice[6] == nil {
			return errors.New("accounts.ProgramState is not set")
		}
		if inst.AccountMetaSlice[7] == nil {
			return errors.New("accounts.PayoutWallet is not set")
		}
		if inst.AccountMetaSlice[8] == nil {
			return errors.New("accounts.TokenProgram is not set")
		}
		if inst.AccountMetaSlice[9] == nil {
			return errors.New("accounts.DataBuffer is not set")
		}
		if inst.AccountMetaSlice[10] == nil {
			return errors.New("accounts.Mint is not set")
		}
	}
	return nil
}

func (inst *AggregatorOpenRound) EncodeToTree(parent ag_treeout.Branches) {
	parent.Child(ag_format.Program(ProgramName, ProgramID)).
		//
		ParentFunc(func(programBranch ag_treeout.Branches) {
			programBranch.Child(ag_format.Instruction("AggregatorOpenRound")).
				//
				ParentFunc(func(instructionBranch ag_treeout.Branches) {

					// Parameters of the instruction:
					instructionBranch.Child("Params[len=1]").ParentFunc(func(paramsBranch ag_treeout.Branches) {
						paramsBranch.Child(ag_format.Param("Params", *inst.Params))
					})

					// Accounts of the instruction:
					instructionBranch.Child("Accounts[len=11]").ParentFunc(func(accountsBranch ag_treeout.Branches) {
						accountsBranch.Child(ag_format.Meta("    aggregator", inst.AccountMetaSlice.Get(0)))
						accountsBranch.Child(ag_format.Meta("         lease", inst.AccountMetaSlice.Get(1)))
						accountsBranch.Child(ag_format.Meta("   oracleQueue", inst.AccountMetaSlice.Get(2)))
						accountsBranch.Child(ag_format.Meta("queueAuthority", inst.AccountMetaSlice.Get(3)))
						accountsBranch.Child(ag_format.Meta("    permission", inst.AccountMetaSlice.Get(4)))
						accountsBranch.Child(ag_format.Meta("        escrow", inst.AccountMetaSlice.Get(5)))
						accountsBranch.Child(ag_format.Meta("  programState", inst.AccountMetaSlice.Get(6)))
						accountsBranch.Child(ag_format.Meta("  payoutWallet", inst.AccountMetaSlice.Get(7)))
						accountsBranch.Child(ag_format.Meta("  tokenProgram", inst.AccountMetaSlice.Get(8)))
						accountsBranch.Child(ag_format.Meta("    dataBuffer", inst.AccountMetaSlice.Get(9)))
						accountsBranch.Child(ag_format.Meta("          mint", inst.AccountMetaSlice.Get(10)))
					})
				})
		})
}

func (obj AggregatorOpenRound) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	// Serialize `Params` param:
	err = encoder.Encode(obj.Params)
	if err != nil {
		return err
	}
	return nil
}
func (obj *AggregatorOpenRound) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	// Deserialize `Params`:
	err = decoder.Decode(&obj.Params)
	if err != nil {
		return err
	}
	return nil
}

// NewAggregatorOpenRoundInstruction declares a new AggregatorOpenRound instruction with the provided parameters and accounts.
func NewAggregatorOpenRoundInstruction(
	// Parameters:
	params AggregatorOpenRoundParams,
	// Accounts:
	aggregator ag_solanago.PublicKey,
	lease ag_solanago.PublicKey,
	oracleQueue ag_solanago.PublicKey,
	queueAuthority ag_solanago.PublicKey,
	permission ag_solanago.PublicKey,
	escrow ag_solanago.PublicKey,
	programState ag_solanago.PublicKey,
	payoutWallet ag_solanago.PublicKey,
	tokenProgram ag_solanago.PublicKey,
	dataBuffer ag_solanago.PublicKey,
	mint ag_solanago.PublicKey) *AggregatorOpenRound {
	return NewAggregatorOpenRoundInstructionBuilder().
		SetParams(params).
		SetAggregatorAccount(aggregator).
		SetLeaseAccount(lease).
		SetOracleQueueAccount(oracleQueue).
		SetQueueAuthorityAccount(queueAuthority).
		SetPermissionAccount(permission).
		SetEscrowAccount(escrow).
		SetProgramStateAccount(programState).
		SetPayoutWalletAccount(payoutWallet).
		SetTokenProgramAccount(tokenProgram).
		SetDataBufferAccount(dataBuffer).
		SetMintAccount(mint)
}
