// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.

package switchboard_v2

import (
	"errors"
	ag_binary "github.com/gagliardetto/binary"
	ag_solanago "github.com/gagliardetto/solana-go"
	ag_format "github.com/gagliardetto/solana-go/text/format"
	ag_treeout "github.com/gagliardetto/treeout"
)

// AggregatorRemoveJob is the `aggregatorRemoveJob` instruction.
type AggregatorRemoveJob struct {
	Params *AggregatorRemoveJobParams

	// [0] = [WRITE] aggregator
	//
	// [1] = [SIGNER] authority
	//
	// [2] = [WRITE] job
	ag_solanago.AccountMetaSlice `bin:"-"`
}

// NewAggregatorRemoveJobInstructionBuilder creates a new `AggregatorRemoveJob` instruction builder.
func NewAggregatorRemoveJobInstructionBuilder() *AggregatorRemoveJob {
	nd := &AggregatorRemoveJob{
		AccountMetaSlice: make(ag_solanago.AccountMetaSlice, 3),
	}
	return nd
}

// SetParams sets the "params" parameter.
func (inst *AggregatorRemoveJob) SetParams(params AggregatorRemoveJobParams) *AggregatorRemoveJob {
	inst.Params = &params
	return inst
}

// SetAggregatorAccount sets the "aggregator" account.
func (inst *AggregatorRemoveJob) SetAggregatorAccount(aggregator ag_solanago.PublicKey) *AggregatorRemoveJob {
	inst.AccountMetaSlice[0] = ag_solanago.Meta(aggregator).WRITE()
	return inst
}

// GetAggregatorAccount gets the "aggregator" account.
func (inst *AggregatorRemoveJob) GetAggregatorAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(0)
}

// SetAuthorityAccount sets the "authority" account.
func (inst *AggregatorRemoveJob) SetAuthorityAccount(authority ag_solanago.PublicKey) *AggregatorRemoveJob {
	inst.AccountMetaSlice[1] = ag_solanago.Meta(authority).SIGNER()
	return inst
}

// GetAuthorityAccount gets the "authority" account.
func (inst *AggregatorRemoveJob) GetAuthorityAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(1)
}

// SetJobAccount sets the "job" account.
func (inst *AggregatorRemoveJob) SetJobAccount(job ag_solanago.PublicKey) *AggregatorRemoveJob {
	inst.AccountMetaSlice[2] = ag_solanago.Meta(job).WRITE()
	return inst
}

// GetJobAccount gets the "job" account.
func (inst *AggregatorRemoveJob) GetJobAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(2)
}

func (inst AggregatorRemoveJob) Build() *Instruction {
	return &Instruction{BaseVariant: ag_binary.BaseVariant{
		Impl:   inst,
		TypeID: Instruction_AggregatorRemoveJob,
	}}
}

// ValidateAndBuild validates the instruction parameters and accounts;
// if there is a validation error, it returns the error.
// Otherwise, it builds and returns the instruction.
func (inst AggregatorRemoveJob) ValidateAndBuild() (*Instruction, error) {
	if err := inst.Validate(); err != nil {
		return nil, err
	}
	return inst.Build(), nil
}

func (inst *AggregatorRemoveJob) Validate() error {
	// Check whether all (required) parameters are set:
	{
		if inst.Params == nil {
			return errors.New("Params parameter is not set")
		}
	}

	// Check whether all (required) accounts are set:
	{
		if inst.AccountMetaSlice[0] == nil {
			return errors.New("accounts.Aggregator is not set")
		}
		if inst.AccountMetaSlice[1] == nil {
			return errors.New("accounts.Authority is not set")
		}
		if inst.AccountMetaSlice[2] == nil {
			return errors.New("accounts.Job is not set")
		}
	}
	return nil
}

func (inst *AggregatorRemoveJob) EncodeToTree(parent ag_treeout.Branches) {
	parent.Child(ag_format.Program(ProgramName, ProgramID)).
		//
		ParentFunc(func(programBranch ag_treeout.Branches) {
			programBranch.Child(ag_format.Instruction("AggregatorRemoveJob")).
				//
				ParentFunc(func(instructionBranch ag_treeout.Branches) {

					// Parameters of the instruction:
					instructionBranch.Child("Params[len=1]").ParentFunc(func(paramsBranch ag_treeout.Branches) {
						paramsBranch.Child(ag_format.Param("Params", *inst.Params))
					})

					// Accounts of the instruction:
					instructionBranch.Child("Accounts[len=3]").ParentFunc(func(accountsBranch ag_treeout.Branches) {
						accountsBranch.Child(ag_format.Meta("aggregator", inst.AccountMetaSlice.Get(0)))
						accountsBranch.Child(ag_format.Meta(" authority", inst.AccountMetaSlice.Get(1)))
						accountsBranch.Child(ag_format.Meta("       job", inst.AccountMetaSlice.Get(2)))
					})
				})
		})
}

func (obj AggregatorRemoveJob) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	// Serialize `Params` param:
	err = encoder.Encode(obj.Params)
	if err != nil {
		return err
	}
	return nil
}
func (obj *AggregatorRemoveJob) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	// Deserialize `Params`:
	err = decoder.Decode(&obj.Params)
	if err != nil {
		return err
	}
	return nil
}

// NewAggregatorRemoveJobInstruction declares a new AggregatorRemoveJob instruction with the provided parameters and accounts.
func NewAggregatorRemoveJobInstruction(
	// Parameters:
	params AggregatorRemoveJobParams,
	// Accounts:
	aggregator ag_solanago.PublicKey,
	authority ag_solanago.PublicKey,
	job ag_solanago.PublicKey) *AggregatorRemoveJob {
	return NewAggregatorRemoveJobInstructionBuilder().
		SetParams(params).
		SetAggregatorAccount(aggregator).
		SetAuthorityAccount(authority).
		SetJobAccount(job)
}
