// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.

package switchboard_v2

import (
	"errors"
	ag_binary "github.com/gagliardetto/binary"
	ag_solanago "github.com/gagliardetto/solana-go"
	ag_format "github.com/gagliardetto/solana-go/text/format"
	ag_treeout "github.com/gagliardetto/treeout"
)

// AggregatorInit is the `aggregatorInit` instruction.
type AggregatorInit struct {
	Params *AggregatorInitParams

	// [0] = [WRITE] aggregator
	//
	// [1] = [] authority
	//
	// [2] = [] queue
	//
	// [3] = [] programState
	ag_solanago.AccountMetaSlice `bin:"-"`
}

// NewAggregatorInitInstructionBuilder creates a new `AggregatorInit` instruction builder.
func NewAggregatorInitInstructionBuilder() *AggregatorInit {
	nd := &AggregatorInit{
		AccountMetaSlice: make(ag_solanago.AccountMetaSlice, 4),
	}
	return nd
}

// SetParams sets the "params" parameter.
func (inst *AggregatorInit) SetParams(params AggregatorInitParams) *AggregatorInit {
	inst.Params = &params
	return inst
}

// SetAggregatorAccount sets the "aggregator" account.
func (inst *AggregatorInit) SetAggregatorAccount(aggregator ag_solanago.PublicKey) *AggregatorInit {
	inst.AccountMetaSlice[0] = ag_solanago.Meta(aggregator).WRITE()
	return inst
}

// GetAggregatorAccount gets the "aggregator" account.
func (inst *AggregatorInit) GetAggregatorAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(0)
}

// SetAuthorityAccount sets the "authority" account.
func (inst *AggregatorInit) SetAuthorityAccount(authority ag_solanago.PublicKey) *AggregatorInit {
	inst.AccountMetaSlice[1] = ag_solanago.Meta(authority)
	return inst
}

// GetAuthorityAccount gets the "authority" account.
func (inst *AggregatorInit) GetAuthorityAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(1)
}

// SetQueueAccount sets the "queue" account.
func (inst *AggregatorInit) SetQueueAccount(queue ag_solanago.PublicKey) *AggregatorInit {
	inst.AccountMetaSlice[2] = ag_solanago.Meta(queue)
	return inst
}

// GetQueueAccount gets the "queue" account.
func (inst *AggregatorInit) GetQueueAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(2)
}

// SetProgramStateAccount sets the "programState" account.
func (inst *AggregatorInit) SetProgramStateAccount(programState ag_solanago.PublicKey) *AggregatorInit {
	inst.AccountMetaSlice[3] = ag_solanago.Meta(programState)
	return inst
}

// GetProgramStateAccount gets the "programState" account.
func (inst *AggregatorInit) GetProgramStateAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(3)
}

func (inst AggregatorInit) Build() *Instruction {
	return &Instruction{BaseVariant: ag_binary.BaseVariant{
		Impl:   inst,
		TypeID: Instruction_AggregatorInit,
	}}
}

// ValidateAndBuild validates the instruction parameters and accounts;
// if there is a validation error, it returns the error.
// Otherwise, it builds and returns the instruction.
func (inst AggregatorInit) ValidateAndBuild() (*Instruction, error) {
	if err := inst.Validate(); err != nil {
		return nil, err
	}
	return inst.Build(), nil
}

func (inst *AggregatorInit) Validate() error {
	// Check whether all (required) parameters are set:
	{
		if inst.Params == nil {
			return errors.New("Params parameter is not set")
		}
	}

	// Check whether all (required) accounts are set:
	{
		if inst.AccountMetaSlice[0] == nil {
			return errors.New("accounts.Aggregator is not set")
		}
		if inst.AccountMetaSlice[1] == nil {
			return errors.New("accounts.Authority is not set")
		}
		if inst.AccountMetaSlice[2] == nil {
			return errors.New("accounts.Queue is not set")
		}
		if inst.AccountMetaSlice[3] == nil {
			return errors.New("accounts.ProgramState is not set")
		}
	}
	return nil
}

func (inst *AggregatorInit) EncodeToTree(parent ag_treeout.Branches) {
	parent.Child(ag_format.Program(ProgramName, ProgramID)).
		//
		ParentFunc(func(programBranch ag_treeout.Branches) {
			programBranch.Child(ag_format.Instruction("AggregatorInit")).
				//
				ParentFunc(func(instructionBranch ag_treeout.Branches) {

					// Parameters of the instruction:
					instructionBranch.Child("Params[len=1]").ParentFunc(func(paramsBranch ag_treeout.Branches) {
						paramsBranch.Child(ag_format.Param("Params", *inst.Params))
					})

					// Accounts of the instruction:
					instructionBranch.Child("Accounts[len=4]").ParentFunc(func(accountsBranch ag_treeout.Branches) {
						accountsBranch.Child(ag_format.Meta("  aggregator", inst.AccountMetaSlice.Get(0)))
						accountsBranch.Child(ag_format.Meta("   authority", inst.AccountMetaSlice.Get(1)))
						accountsBranch.Child(ag_format.Meta("       queue", inst.AccountMetaSlice.Get(2)))
						accountsBranch.Child(ag_format.Meta("programState", inst.AccountMetaSlice.Get(3)))
					})
				})
		})
}

func (obj AggregatorInit) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	// Serialize `Params` param:
	err = encoder.Encode(obj.Params)
	if err != nil {
		return err
	}
	return nil
}
func (obj *AggregatorInit) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	// Deserialize `Params`:
	err = decoder.Decode(&obj.Params)
	if err != nil {
		return err
	}
	return nil
}

// NewAggregatorInitInstruction declares a new AggregatorInit instruction with the provided parameters and accounts.
func NewAggregatorInitInstruction(
	// Parameters:
	params AggregatorInitParams,
	// Accounts:
	aggregator ag_solanago.PublicKey,
	authority ag_solanago.PublicKey,
	queue ag_solanago.PublicKey,
	programState ag_solanago.PublicKey) *AggregatorInit {
	return NewAggregatorInitInstructionBuilder().
		SetParams(params).
		SetAggregatorAccount(aggregator).
		SetAuthorityAccount(authority).
		SetQueueAccount(queue).
		SetProgramStateAccount(programState)
}
