// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.

package switchboard_v2

import (
	"errors"
	ag_binary "github.com/gagliardetto/binary"
	ag_solanago "github.com/gagliardetto/solana-go"
	ag_format "github.com/gagliardetto/solana-go/text/format"
	ag_treeout "github.com/gagliardetto/treeout"
)

// AggregatorSetConfig is the `aggregatorSetConfig` instruction.
type AggregatorSetConfig struct {
	Params *AggregatorSetConfigParams

	// [0] = [WRITE] aggregator
	//
	// [1] = [SIGNER] authority
	ag_solanago.AccountMetaSlice `bin:"-"`
}

// NewAggregatorSetConfigInstructionBuilder creates a new `AggregatorSetConfig` instruction builder.
func NewAggregatorSetConfigInstructionBuilder() *AggregatorSetConfig {
	nd := &AggregatorSetConfig{
		AccountMetaSlice: make(ag_solanago.AccountMetaSlice, 2),
	}
	return nd
}

// SetParams sets the "params" parameter.
func (inst *AggregatorSetConfig) SetParams(params AggregatorSetConfigParams) *AggregatorSetConfig {
	inst.Params = &params
	return inst
}

// SetAggregatorAccount sets the "aggregator" account.
func (inst *AggregatorSetConfig) SetAggregatorAccount(aggregator ag_solanago.PublicKey) *AggregatorSetConfig {
	inst.AccountMetaSlice[0] = ag_solanago.Meta(aggregator).WRITE()
	return inst
}

// GetAggregatorAccount gets the "aggregator" account.
func (inst *AggregatorSetConfig) GetAggregatorAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(0)
}

// SetAuthorityAccount sets the "authority" account.
func (inst *AggregatorSetConfig) SetAuthorityAccount(authority ag_solanago.PublicKey) *AggregatorSetConfig {
	inst.AccountMetaSlice[1] = ag_solanago.Meta(authority).SIGNER()
	return inst
}

// GetAuthorityAccount gets the "authority" account.
func (inst *AggregatorSetConfig) GetAuthorityAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(1)
}

func (inst AggregatorSetConfig) Build() *Instruction {
	return &Instruction{BaseVariant: ag_binary.BaseVariant{
		Impl:   inst,
		TypeID: Instruction_AggregatorSetConfig,
	}}
}

// ValidateAndBuild validates the instruction parameters and accounts;
// if there is a validation error, it returns the error.
// Otherwise, it builds and returns the instruction.
func (inst AggregatorSetConfig) ValidateAndBuild() (*Instruction, error) {
	if err := inst.Validate(); err != nil {
		return nil, err
	}
	return inst.Build(), nil
}

func (inst *AggregatorSetConfig) Validate() error {
	// Check whether all (required) parameters are set:
	{
		if inst.Params == nil {
			return errors.New("Params parameter is not set")
		}
	}

	// Check whether all (required) accounts are set:
	{
		if inst.AccountMetaSlice[0] == nil {
			return errors.New("accounts.Aggregator is not set")
		}
		if inst.AccountMetaSlice[1] == nil {
			return errors.New("accounts.Authority is not set")
		}
	}
	return nil
}

func (inst *AggregatorSetConfig) EncodeToTree(parent ag_treeout.Branches) {
	parent.Child(ag_format.Program(ProgramName, ProgramID)).
		//
		ParentFunc(func(programBranch ag_treeout.Branches) {
			programBranch.Child(ag_format.Instruction("AggregatorSetConfig")).
				//
				ParentFunc(func(instructionBranch ag_treeout.Branches) {

					// Parameters of the instruction:
					instructionBranch.Child("Params[len=1]").ParentFunc(func(paramsBranch ag_treeout.Branches) {
						paramsBranch.Child(ag_format.Param("Params", *inst.Params))
					})

					// Accounts of the instruction:
					instructionBranch.Child("Accounts[len=2]").ParentFunc(func(accountsBranch ag_treeout.Branches) {
						accountsBranch.Child(ag_format.Meta("aggregator", inst.AccountMetaSlice.Get(0)))
						accountsBranch.Child(ag_format.Meta(" authority", inst.AccountMetaSlice.Get(1)))
					})
				})
		})
}

func (obj AggregatorSetConfig) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	// Serialize `Params` param:
	err = encoder.Encode(obj.Params)
	if err != nil {
		return err
	}
	return nil
}
func (obj *AggregatorSetConfig) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	// Deserialize `Params`:
	err = decoder.Decode(&obj.Params)
	if err != nil {
		return err
	}
	return nil
}

// NewAggregatorSetConfigInstruction declares a new AggregatorSetConfig instruction with the provided parameters and accounts.
func NewAggregatorSetConfigInstruction(
	// Parameters:
	params AggregatorSetConfigParams,
	// Accounts:
	aggregator ag_solanago.PublicKey,
	authority ag_solanago.PublicKey) *AggregatorSetConfig {
	return NewAggregatorSetConfigInstructionBuilder().
		SetParams(params).
		SetAggregatorAccount(aggregator).
		SetAuthorityAccount(authority)
}
