// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.

package switchboard_v2

import (
	"errors"
	ag_binary "github.com/gagliardetto/binary"
	ag_solanago "github.com/gagliardetto/solana-go"
	ag_format "github.com/gagliardetto/solana-go/text/format"
	ag_treeout "github.com/gagliardetto/treeout"
)

// BufferRelayerInit is the `bufferRelayerInit` instruction.
type BufferRelayerInit struct {
	Params *BufferRelayerInitParams

	// [0] = [WRITE] bufferRelayer
	//
	// [1] = [WRITE] escrow
	//
	// [2] = [] authority
	//
	// [3] = [] queue
	//
	// [4] = [] job
	//
	// [5] = [] programState
	//
	// [6] = [] mint
	//
	// [7] = [WRITE, SIGNER] payer
	//
	// [8] = [] tokenProgram
	//
	// [9] = [] associatedTokenProgram
	//
	// [10] = [] systemProgram
	//
	// [11] = [] rent
	ag_solanago.AccountMetaSlice `bin:"-"`
}

// NewBufferRelayerInitInstructionBuilder creates a new `BufferRelayerInit` instruction builder.
func NewBufferRelayerInitInstructionBuilder() *BufferRelayerInit {
	nd := &BufferRelayerInit{
		AccountMetaSlice: make(ag_solanago.AccountMetaSlice, 12),
	}
	return nd
}

// SetParams sets the "params" parameter.
func (inst *BufferRelayerInit) SetParams(params BufferRelayerInitParams) *BufferRelayerInit {
	inst.Params = &params
	return inst
}

// SetBufferRelayerAccount sets the "bufferRelayer" account.
func (inst *BufferRelayerInit) SetBufferRelayerAccount(bufferRelayer ag_solanago.PublicKey) *BufferRelayerInit {
	inst.AccountMetaSlice[0] = ag_solanago.Meta(bufferRelayer).WRITE()
	return inst
}

// GetBufferRelayerAccount gets the "bufferRelayer" account.
func (inst *BufferRelayerInit) GetBufferRelayerAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(0)
}

// SetEscrowAccount sets the "escrow" account.
func (inst *BufferRelayerInit) SetEscrowAccount(escrow ag_solanago.PublicKey) *BufferRelayerInit {
	inst.AccountMetaSlice[1] = ag_solanago.Meta(escrow).WRITE()
	return inst
}

// GetEscrowAccount gets the "escrow" account.
func (inst *BufferRelayerInit) GetEscrowAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(1)
}

// SetAuthorityAccount sets the "authority" account.
func (inst *BufferRelayerInit) SetAuthorityAccount(authority ag_solanago.PublicKey) *BufferRelayerInit {
	inst.AccountMetaSlice[2] = ag_solanago.Meta(authority)
	return inst
}

// GetAuthorityAccount gets the "authority" account.
func (inst *BufferRelayerInit) GetAuthorityAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(2)
}

// SetQueueAccount sets the "queue" account.
func (inst *BufferRelayerInit) SetQueueAccount(queue ag_solanago.PublicKey) *BufferRelayerInit {
	inst.AccountMetaSlice[3] = ag_solanago.Meta(queue)
	return inst
}

// GetQueueAccount gets the "queue" account.
func (inst *BufferRelayerInit) GetQueueAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(3)
}

// SetJobAccount sets the "job" account.
func (inst *BufferRelayerInit) SetJobAccount(job ag_solanago.PublicKey) *BufferRelayerInit {
	inst.AccountMetaSlice[4] = ag_solanago.Meta(job)
	return inst
}

// GetJobAccount gets the "job" account.
func (inst *BufferRelayerInit) GetJobAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(4)
}

// SetProgramStateAccount sets the "programState" account.
func (inst *BufferRelayerInit) SetProgramStateAccount(programState ag_solanago.PublicKey) *BufferRelayerInit {
	inst.AccountMetaSlice[5] = ag_solanago.Meta(programState)
	return inst
}

// GetProgramStateAccount gets the "programState" account.
func (inst *BufferRelayerInit) GetProgramStateAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(5)
}

// SetMintAccount sets the "mint" account.
func (inst *BufferRelayerInit) SetMintAccount(mint ag_solanago.PublicKey) *BufferRelayerInit {
	inst.AccountMetaSlice[6] = ag_solanago.Meta(mint)
	return inst
}

// GetMintAccount gets the "mint" account.
func (inst *BufferRelayerInit) GetMintAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(6)
}

// SetPayerAccount sets the "payer" account.
func (inst *BufferRelayerInit) SetPayerAccount(payer ag_solanago.PublicKey) *BufferRelayerInit {
	inst.AccountMetaSlice[7] = ag_solanago.Meta(payer).WRITE().SIGNER()
	return inst
}

// GetPayerAccount gets the "payer" account.
func (inst *BufferRelayerInit) GetPayerAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(7)
}

// SetTokenProgramAccount sets the "tokenProgram" account.
func (inst *BufferRelayerInit) SetTokenProgramAccount(tokenProgram ag_solanago.PublicKey) *BufferRelayerInit {
	inst.AccountMetaSlice[8] = ag_solanago.Meta(tokenProgram)
	return inst
}

// GetTokenProgramAccount gets the "tokenProgram" account.
func (inst *BufferRelayerInit) GetTokenProgramAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(8)
}

// SetAssociatedTokenProgramAccount sets the "associatedTokenProgram" account.
func (inst *BufferRelayerInit) SetAssociatedTokenProgramAccount(associatedTokenProgram ag_solanago.PublicKey) *BufferRelayerInit {
	inst.AccountMetaSlice[9] = ag_solanago.Meta(associatedTokenProgram)
	return inst
}

// GetAssociatedTokenProgramAccount gets the "associatedTokenProgram" account.
func (inst *BufferRelayerInit) GetAssociatedTokenProgramAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(9)
}

// SetSystemProgramAccount sets the "systemProgram" account.
func (inst *BufferRelayerInit) SetSystemProgramAccount(systemProgram ag_solanago.PublicKey) *BufferRelayerInit {
	inst.AccountMetaSlice[10] = ag_solanago.Meta(systemProgram)
	return inst
}

// GetSystemProgramAccount gets the "systemProgram" account.
func (inst *BufferRelayerInit) GetSystemProgramAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(10)
}

// SetRentAccount sets the "rent" account.
func (inst *BufferRelayerInit) SetRentAccount(rent ag_solanago.PublicKey) *BufferRelayerInit {
	inst.AccountMetaSlice[11] = ag_solanago.Meta(rent)
	return inst
}

// GetRentAccount gets the "rent" account.
func (inst *BufferRelayerInit) GetRentAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(11)
}

func (inst BufferRelayerInit) Build() *Instruction {
	return &Instruction{BaseVariant: ag_binary.BaseVariant{
		Impl:   inst,
		TypeID: Instruction_BufferRelayerInit,
	}}
}

// ValidateAndBuild validates the instruction parameters and accounts;
// if there is a validation error, it returns the error.
// Otherwise, it builds and returns the instruction.
func (inst BufferRelayerInit) ValidateAndBuild() (*Instruction, error) {
	if err := inst.Validate(); err != nil {
		return nil, err
	}
	return inst.Build(), nil
}

func (inst *BufferRelayerInit) Validate() error {
	// Check whether all (required) parameters are set:
	{
		if inst.Params == nil {
			return errors.New("Params parameter is not set")
		}
	}

	// Check whether all (required) accounts are set:
	{
		if inst.AccountMetaSlice[0] == nil {
			return errors.New("accounts.BufferRelayer is not set")
		}
		if inst.AccountMetaSlice[1] == nil {
			return errors.New("accounts.Escrow is not set")
		}
		if inst.AccountMetaSlice[2] == nil {
			return errors.New("accounts.Authority is not set")
		}
		if inst.AccountMetaSlice[3] == nil {
			return errors.New("accounts.Queue is not set")
		}
		if inst.AccountMetaSlice[4] == nil {
			return errors.New("accounts.Job is not set")
		}
		if inst.AccountMetaSlice[5] == nil {
			return errors.New("accounts.ProgramState is not set")
		}
		if inst.AccountMetaSlice[6] == nil {
			return errors.New("accounts.Mint is not set")
		}
		if inst.AccountMetaSlice[7] == nil {
			return errors.New("accounts.Payer is not set")
		}
		if inst.AccountMetaSlice[8] == nil {
			return errors.New("accounts.TokenProgram is not set")
		}
		if inst.AccountMetaSlice[9] == nil {
			return errors.New("accounts.AssociatedTokenProgram is not set")
		}
		if inst.AccountMetaSlice[10] == nil {
			return errors.New("accounts.SystemProgram is not set")
		}
		if inst.AccountMetaSlice[11] == nil {
			return errors.New("accounts.Rent is not set")
		}
	}
	return nil
}

func (inst *BufferRelayerInit) EncodeToTree(parent ag_treeout.Branches) {
	parent.Child(ag_format.Program(ProgramName, ProgramID)).
		//
		ParentFunc(func(programBranch ag_treeout.Branches) {
			programBranch.Child(ag_format.Instruction("BufferRelayerInit")).
				//
				ParentFunc(func(instructionBranch ag_treeout.Branches) {

					// Parameters of the instruction:
					instructionBranch.Child("Params[len=1]").ParentFunc(func(paramsBranch ag_treeout.Branches) {
						paramsBranch.Child(ag_format.Param("Params", *inst.Params))
					})

					// Accounts of the instruction:
					instructionBranch.Child("Accounts[len=12]").ParentFunc(func(accountsBranch ag_treeout.Branches) {
						accountsBranch.Child(ag_format.Meta("         bufferRelayer", inst.AccountMetaSlice.Get(0)))
						accountsBranch.Child(ag_format.Meta("                escrow", inst.AccountMetaSlice.Get(1)))
						accountsBranch.Child(ag_format.Meta("             authority", inst.AccountMetaSlice.Get(2)))
						accountsBranch.Child(ag_format.Meta("                 queue", inst.AccountMetaSlice.Get(3)))
						accountsBranch.Child(ag_format.Meta("                   job", inst.AccountMetaSlice.Get(4)))
						accountsBranch.Child(ag_format.Meta("          programState", inst.AccountMetaSlice.Get(5)))
						accountsBranch.Child(ag_format.Meta("                  mint", inst.AccountMetaSlice.Get(6)))
						accountsBranch.Child(ag_format.Meta("                 payer", inst.AccountMetaSlice.Get(7)))
						accountsBranch.Child(ag_format.Meta("          tokenProgram", inst.AccountMetaSlice.Get(8)))
						accountsBranch.Child(ag_format.Meta("associatedTokenProgram", inst.AccountMetaSlice.Get(9)))
						accountsBranch.Child(ag_format.Meta("         systemProgram", inst.AccountMetaSlice.Get(10)))
						accountsBranch.Child(ag_format.Meta("                  rent", inst.AccountMetaSlice.Get(11)))
					})
				})
		})
}

func (obj BufferRelayerInit) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	// Serialize `Params` param:
	err = encoder.Encode(obj.Params)
	if err != nil {
		return err
	}
	return nil
}
func (obj *BufferRelayerInit) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	// Deserialize `Params`:
	err = decoder.Decode(&obj.Params)
	if err != nil {
		return err
	}
	return nil
}

// NewBufferRelayerInitInstruction declares a new BufferRelayerInit instruction with the provided parameters and accounts.
func NewBufferRelayerInitInstruction(
	// Parameters:
	params BufferRelayerInitParams,
	// Accounts:
	bufferRelayer ag_solanago.PublicKey,
	escrow ag_solanago.PublicKey,
	authority ag_solanago.PublicKey,
	queue ag_solanago.PublicKey,
	job ag_solanago.PublicKey,
	programState ag_solanago.PublicKey,
	mint ag_solanago.PublicKey,
	payer ag_solanago.PublicKey,
	tokenProgram ag_solanago.PublicKey,
	associatedTokenProgram ag_solanago.PublicKey,
	systemProgram ag_solanago.PublicKey,
	rent ag_solanago.PublicKey) *BufferRelayerInit {
	return NewBufferRelayerInitInstructionBuilder().
		SetParams(params).
		SetBufferRelayerAccount(bufferRelayer).
		SetEscrowAccount(escrow).
		SetAuthorityAccount(authority).
		SetQueueAccount(queue).
		SetJobAccount(job).
		SetProgramStateAccount(programState).
		SetMintAccount(mint).
		SetPayerAccount(payer).
		SetTokenProgramAccount(tokenProgram).
		SetAssociatedTokenProgramAccount(associatedTokenProgram).
		SetSystemProgramAccount(systemProgram).
		SetRentAccount(rent)
}
