// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.

package switchboard_v2

import (
	"errors"
	ag_binary "github.com/gagliardetto/binary"
	ag_solanago "github.com/gagliardetto/solana-go"
	ag_format "github.com/gagliardetto/solana-go/text/format"
	ag_treeout "github.com/gagliardetto/treeout"
)

// CrankPush is the `crankPush` instruction.
type CrankPush struct {
	Params *CrankPushParams

	// [0] = [WRITE] crank
	//
	// [1] = [WRITE] aggregator
	//
	// [2] = [WRITE] oracleQueue
	//
	// [3] = [] queueAuthority
	//
	// [4] = [] permission
	//
	// [5] = [WRITE] lease
	//
	// [6] = [WRITE] escrow
	//
	// [7] = [] programState
	//
	// [8] = [WRITE] dataBuffer
	ag_solanago.AccountMetaSlice `bin:"-"`
}

// NewCrankPushInstructionBuilder creates a new `CrankPush` instruction builder.
func NewCrankPushInstructionBuilder() *CrankPush {
	nd := &CrankPush{
		AccountMetaSlice: make(ag_solanago.AccountMetaSlice, 9),
	}
	return nd
}

// SetParams sets the "params" parameter.
func (inst *CrankPush) SetParams(params CrankPushParams) *CrankPush {
	inst.Params = &params
	return inst
}

// SetCrankAccount sets the "crank" account.
func (inst *CrankPush) SetCrankAccount(crank ag_solanago.PublicKey) *CrankPush {
	inst.AccountMetaSlice[0] = ag_solanago.Meta(crank).WRITE()
	return inst
}

// GetCrankAccount gets the "crank" account.
func (inst *CrankPush) GetCrankAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(0)
}

// SetAggregatorAccount sets the "aggregator" account.
func (inst *CrankPush) SetAggregatorAccount(aggregator ag_solanago.PublicKey) *CrankPush {
	inst.AccountMetaSlice[1] = ag_solanago.Meta(aggregator).WRITE()
	return inst
}

// GetAggregatorAccount gets the "aggregator" account.
func (inst *CrankPush) GetAggregatorAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(1)
}

// SetOracleQueueAccount sets the "oracleQueue" account.
func (inst *CrankPush) SetOracleQueueAccount(oracleQueue ag_solanago.PublicKey) *CrankPush {
	inst.AccountMetaSlice[2] = ag_solanago.Meta(oracleQueue).WRITE()
	return inst
}

// GetOracleQueueAccount gets the "oracleQueue" account.
func (inst *CrankPush) GetOracleQueueAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(2)
}

// SetQueueAuthorityAccount sets the "queueAuthority" account.
func (inst *CrankPush) SetQueueAuthorityAccount(queueAuthority ag_solanago.PublicKey) *CrankPush {
	inst.AccountMetaSlice[3] = ag_solanago.Meta(queueAuthority)
	return inst
}

// GetQueueAuthorityAccount gets the "queueAuthority" account.
func (inst *CrankPush) GetQueueAuthorityAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(3)
}

// SetPermissionAccount sets the "permission" account.
func (inst *CrankPush) SetPermissionAccount(permission ag_solanago.PublicKey) *CrankPush {
	inst.AccountMetaSlice[4] = ag_solanago.Meta(permission)
	return inst
}

// GetPermissionAccount gets the "permission" account.
func (inst *CrankPush) GetPermissionAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(4)
}

// SetLeaseAccount sets the "lease" account.
func (inst *CrankPush) SetLeaseAccount(lease ag_solanago.PublicKey) *CrankPush {
	inst.AccountMetaSlice[5] = ag_solanago.Meta(lease).WRITE()
	return inst
}

// GetLeaseAccount gets the "lease" account.
func (inst *CrankPush) GetLeaseAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(5)
}

// SetEscrowAccount sets the "escrow" account.
func (inst *CrankPush) SetEscrowAccount(escrow ag_solanago.PublicKey) *CrankPush {
	inst.AccountMetaSlice[6] = ag_solanago.Meta(escrow).WRITE()
	return inst
}

// GetEscrowAccount gets the "escrow" account.
func (inst *CrankPush) GetEscrowAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(6)
}

// SetProgramStateAccount sets the "programState" account.
func (inst *CrankPush) SetProgramStateAccount(programState ag_solanago.PublicKey) *CrankPush {
	inst.AccountMetaSlice[7] = ag_solanago.Meta(programState)
	return inst
}

// GetProgramStateAccount gets the "programState" account.
func (inst *CrankPush) GetProgramStateAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(7)
}

// SetDataBufferAccount sets the "dataBuffer" account.
func (inst *CrankPush) SetDataBufferAccount(dataBuffer ag_solanago.PublicKey) *CrankPush {
	inst.AccountMetaSlice[8] = ag_solanago.Meta(dataBuffer).WRITE()
	return inst
}

// GetDataBufferAccount gets the "dataBuffer" account.
func (inst *CrankPush) GetDataBufferAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(8)
}

func (inst CrankPush) Build() *Instruction {
	return &Instruction{BaseVariant: ag_binary.BaseVariant{
		Impl:   inst,
		TypeID: Instruction_CrankPush,
	}}
}

// ValidateAndBuild validates the instruction parameters and accounts;
// if there is a validation error, it returns the error.
// Otherwise, it builds and returns the instruction.
func (inst CrankPush) ValidateAndBuild() (*Instruction, error) {
	if err := inst.Validate(); err != nil {
		return nil, err
	}
	return inst.Build(), nil
}

func (inst *CrankPush) Validate() error {
	// Check whether all (required) parameters are set:
	{
		if inst.Params == nil {
			return errors.New("Params parameter is not set")
		}
	}

	// Check whether all (required) accounts are set:
	{
		if inst.AccountMetaSlice[0] == nil {
			return errors.New("accounts.Crank is not set")
		}
		if inst.AccountMetaSlice[1] == nil {
			return errors.New("accounts.Aggregator is not set")
		}
		if inst.AccountMetaSlice[2] == nil {
			return errors.New("accounts.OracleQueue is not set")
		}
		if inst.AccountMetaSlice[3] == nil {
			return errors.New("accounts.QueueAuthority is not set")
		}
		if inst.AccountMetaSlice[4] == nil {
			return errors.New("accounts.Permission is not set")
		}
		if inst.AccountMetaSlice[5] == nil {
			return errors.New("accounts.Lease is not set")
		}
		if inst.AccountMetaSlice[6] == nil {
			return errors.New("accounts.Escrow is not set")
		}
		if inst.AccountMetaSlice[7] == nil {
			return errors.New("accounts.ProgramState is not set")
		}
		if inst.AccountMetaSlice[8] == nil {
			return errors.New("accounts.DataBuffer is not set")
		}
	}
	return nil
}

func (inst *CrankPush) EncodeToTree(parent ag_treeout.Branches) {
	parent.Child(ag_format.Program(ProgramName, ProgramID)).
		//
		ParentFunc(func(programBranch ag_treeout.Branches) {
			programBranch.Child(ag_format.Instruction("CrankPush")).
				//
				ParentFunc(func(instructionBranch ag_treeout.Branches) {

					// Parameters of the instruction:
					instructionBranch.Child("Params[len=1]").ParentFunc(func(paramsBranch ag_treeout.Branches) {
						paramsBranch.Child(ag_format.Param("Params", *inst.Params))
					})

					// Accounts of the instruction:
					instructionBranch.Child("Accounts[len=9]").ParentFunc(func(accountsBranch ag_treeout.Branches) {
						accountsBranch.Child(ag_format.Meta("         crank", inst.AccountMetaSlice.Get(0)))
						accountsBranch.Child(ag_format.Meta("    aggregator", inst.AccountMetaSlice.Get(1)))
						accountsBranch.Child(ag_format.Meta("   oracleQueue", inst.AccountMetaSlice.Get(2)))
						accountsBranch.Child(ag_format.Meta("queueAuthority", inst.AccountMetaSlice.Get(3)))
						accountsBranch.Child(ag_format.Meta("    permission", inst.AccountMetaSlice.Get(4)))
						accountsBranch.Child(ag_format.Meta("         lease", inst.AccountMetaSlice.Get(5)))
						accountsBranch.Child(ag_format.Meta("        escrow", inst.AccountMetaSlice.Get(6)))
						accountsBranch.Child(ag_format.Meta("  programState", inst.AccountMetaSlice.Get(7)))
						accountsBranch.Child(ag_format.Meta("    dataBuffer", inst.AccountMetaSlice.Get(8)))
					})
				})
		})
}

func (obj CrankPush) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	// Serialize `Params` param:
	err = encoder.Encode(obj.Params)
	if err != nil {
		return err
	}
	return nil
}
func (obj *CrankPush) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	// Deserialize `Params`:
	err = decoder.Decode(&obj.Params)
	if err != nil {
		return err
	}
	return nil
}

// NewCrankPushInstruction declares a new CrankPush instruction with the provided parameters and accounts.
func NewCrankPushInstruction(
	// Parameters:
	params CrankPushParams,
	// Accounts:
	crank ag_solanago.PublicKey,
	aggregator ag_solanago.PublicKey,
	oracleQueue ag_solanago.PublicKey,
	queueAuthority ag_solanago.PublicKey,
	permission ag_solanago.PublicKey,
	lease ag_solanago.PublicKey,
	escrow ag_solanago.PublicKey,
	programState ag_solanago.PublicKey,
	dataBuffer ag_solanago.PublicKey) *CrankPush {
	return NewCrankPushInstructionBuilder().
		SetParams(params).
		SetCrankAccount(crank).
		SetAggregatorAccount(aggregator).
		SetOracleQueueAccount(oracleQueue).
		SetQueueAuthorityAccount(queueAuthority).
		SetPermissionAccount(permission).
		SetLeaseAccount(lease).
		SetEscrowAccount(escrow).
		SetProgramStateAccount(programState).
		SetDataBufferAccount(dataBuffer)
}
