// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.

package switchboard_v2

import (
	"errors"
	ag_binary "github.com/gagliardetto/binary"
	ag_solanago "github.com/gagliardetto/solana-go"
	ag_format "github.com/gagliardetto/solana-go/text/format"
	ag_treeout "github.com/gagliardetto/treeout"
)

// LeaseInit is the `leaseInit` instruction.
type LeaseInit struct {
	Params *LeaseInitParams

	// [0] = [WRITE] lease
	//
	// [1] = [WRITE] queue
	//
	// [2] = [] aggregator
	//
	// [3] = [WRITE] funder
	//
	// [4] = [WRITE, SIGNER] payer
	//
	// [5] = [] systemProgram
	//
	// [6] = [] tokenProgram
	//
	// [7] = [WRITE, SIGNER] owner
	//
	// [8] = [WRITE] escrow
	//
	// [9] = [] programState
	//
	// [10] = [] mint
	ag_solanago.AccountMetaSlice `bin:"-"`
}

// NewLeaseInitInstructionBuilder creates a new `LeaseInit` instruction builder.
func NewLeaseInitInstructionBuilder() *LeaseInit {
	nd := &LeaseInit{
		AccountMetaSlice: make(ag_solanago.AccountMetaSlice, 11),
	}
	return nd
}

// SetParams sets the "params" parameter.
func (inst *LeaseInit) SetParams(params LeaseInitParams) *LeaseInit {
	inst.Params = &params
	return inst
}

// SetLeaseAccount sets the "lease" account.
func (inst *LeaseInit) SetLeaseAccount(lease ag_solanago.PublicKey) *LeaseInit {
	inst.AccountMetaSlice[0] = ag_solanago.Meta(lease).WRITE()
	return inst
}

// GetLeaseAccount gets the "lease" account.
func (inst *LeaseInit) GetLeaseAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(0)
}

// SetQueueAccount sets the "queue" account.
func (inst *LeaseInit) SetQueueAccount(queue ag_solanago.PublicKey) *LeaseInit {
	inst.AccountMetaSlice[1] = ag_solanago.Meta(queue).WRITE()
	return inst
}

// GetQueueAccount gets the "queue" account.
func (inst *LeaseInit) GetQueueAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(1)
}

// SetAggregatorAccount sets the "aggregator" account.
func (inst *LeaseInit) SetAggregatorAccount(aggregator ag_solanago.PublicKey) *LeaseInit {
	inst.AccountMetaSlice[2] = ag_solanago.Meta(aggregator)
	return inst
}

// GetAggregatorAccount gets the "aggregator" account.
func (inst *LeaseInit) GetAggregatorAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(2)
}

// SetFunderAccount sets the "funder" account.
func (inst *LeaseInit) SetFunderAccount(funder ag_solanago.PublicKey) *LeaseInit {
	inst.AccountMetaSlice[3] = ag_solanago.Meta(funder).WRITE()
	return inst
}

// GetFunderAccount gets the "funder" account.
func (inst *LeaseInit) GetFunderAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(3)
}

// SetPayerAccount sets the "payer" account.
func (inst *LeaseInit) SetPayerAccount(payer ag_solanago.PublicKey) *LeaseInit {
	inst.AccountMetaSlice[4] = ag_solanago.Meta(payer).WRITE().SIGNER()
	return inst
}

// GetPayerAccount gets the "payer" account.
func (inst *LeaseInit) GetPayerAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(4)
}

// SetSystemProgramAccount sets the "systemProgram" account.
func (inst *LeaseInit) SetSystemProgramAccount(systemProgram ag_solanago.PublicKey) *LeaseInit {
	inst.AccountMetaSlice[5] = ag_solanago.Meta(systemProgram)
	return inst
}

// GetSystemProgramAccount gets the "systemProgram" account.
func (inst *LeaseInit) GetSystemProgramAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(5)
}

// SetTokenProgramAccount sets the "tokenProgram" account.
func (inst *LeaseInit) SetTokenProgramAccount(tokenProgram ag_solanago.PublicKey) *LeaseInit {
	inst.AccountMetaSlice[6] = ag_solanago.Meta(tokenProgram)
	return inst
}

// GetTokenProgramAccount gets the "tokenProgram" account.
func (inst *LeaseInit) GetTokenProgramAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(6)
}

// SetOwnerAccount sets the "owner" account.
func (inst *LeaseInit) SetOwnerAccount(owner ag_solanago.PublicKey) *LeaseInit {
	inst.AccountMetaSlice[7] = ag_solanago.Meta(owner).WRITE().SIGNER()
	return inst
}

// GetOwnerAccount gets the "owner" account.
func (inst *LeaseInit) GetOwnerAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(7)
}

// SetEscrowAccount sets the "escrow" account.
func (inst *LeaseInit) SetEscrowAccount(escrow ag_solanago.PublicKey) *LeaseInit {
	inst.AccountMetaSlice[8] = ag_solanago.Meta(escrow).WRITE()
	return inst
}

// GetEscrowAccount gets the "escrow" account.
func (inst *LeaseInit) GetEscrowAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(8)
}

// SetProgramStateAccount sets the "programState" account.
func (inst *LeaseInit) SetProgramStateAccount(programState ag_solanago.PublicKey) *LeaseInit {
	inst.AccountMetaSlice[9] = ag_solanago.Meta(programState)
	return inst
}

// GetProgramStateAccount gets the "programState" account.
func (inst *LeaseInit) GetProgramStateAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(9)
}

// SetMintAccount sets the "mint" account.
func (inst *LeaseInit) SetMintAccount(mint ag_solanago.PublicKey) *LeaseInit {
	inst.AccountMetaSlice[10] = ag_solanago.Meta(mint)
	return inst
}

// GetMintAccount gets the "mint" account.
func (inst *LeaseInit) GetMintAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(10)
}

func (inst LeaseInit) Build() *Instruction {
	return &Instruction{BaseVariant: ag_binary.BaseVariant{
		Impl:   inst,
		TypeID: Instruction_LeaseInit,
	}}
}

// ValidateAndBuild validates the instruction parameters and accounts;
// if there is a validation error, it returns the error.
// Otherwise, it builds and returns the instruction.
func (inst LeaseInit) ValidateAndBuild() (*Instruction, error) {
	if err := inst.Validate(); err != nil {
		return nil, err
	}
	return inst.Build(), nil
}

func (inst *LeaseInit) Validate() error {
	// Check whether all (required) parameters are set:
	{
		if inst.Params == nil {
			return errors.New("Params parameter is not set")
		}
	}

	// Check whether all (required) accounts are set:
	{
		if inst.AccountMetaSlice[0] == nil {
			return errors.New("accounts.Lease is not set")
		}
		if inst.AccountMetaSlice[1] == nil {
			return errors.New("accounts.Queue is not set")
		}
		if inst.AccountMetaSlice[2] == nil {
			return errors.New("accounts.Aggregator is not set")
		}
		if inst.AccountMetaSlice[3] == nil {
			return errors.New("accounts.Funder is not set")
		}
		if inst.AccountMetaSlice[4] == nil {
			return errors.New("accounts.Payer is not set")
		}
		if inst.AccountMetaSlice[5] == nil {
			return errors.New("accounts.SystemProgram is not set")
		}
		if inst.AccountMetaSlice[6] == nil {
			return errors.New("accounts.TokenProgram is not set")
		}
		if inst.AccountMetaSlice[7] == nil {
			return errors.New("accounts.Owner is not set")
		}
		if inst.AccountMetaSlice[8] == nil {
			return errors.New("accounts.Escrow is not set")
		}
		if inst.AccountMetaSlice[9] == nil {
			return errors.New("accounts.ProgramState is not set")
		}
		if inst.AccountMetaSlice[10] == nil {
			return errors.New("accounts.Mint is not set")
		}
	}
	return nil
}

func (inst *LeaseInit) EncodeToTree(parent ag_treeout.Branches) {
	parent.Child(ag_format.Program(ProgramName, ProgramID)).
		//
		ParentFunc(func(programBranch ag_treeout.Branches) {
			programBranch.Child(ag_format.Instruction("LeaseInit")).
				//
				ParentFunc(func(instructionBranch ag_treeout.Branches) {

					// Parameters of the instruction:
					instructionBranch.Child("Params[len=1]").ParentFunc(func(paramsBranch ag_treeout.Branches) {
						paramsBranch.Child(ag_format.Param("Params", *inst.Params))
					})

					// Accounts of the instruction:
					instructionBranch.Child("Accounts[len=11]").ParentFunc(func(accountsBranch ag_treeout.Branches) {
						accountsBranch.Child(ag_format.Meta("        lease", inst.AccountMetaSlice.Get(0)))
						accountsBranch.Child(ag_format.Meta("        queue", inst.AccountMetaSlice.Get(1)))
						accountsBranch.Child(ag_format.Meta("   aggregator", inst.AccountMetaSlice.Get(2)))
						accountsBranch.Child(ag_format.Meta("       funder", inst.AccountMetaSlice.Get(3)))
						accountsBranch.Child(ag_format.Meta("        payer", inst.AccountMetaSlice.Get(4)))
						accountsBranch.Child(ag_format.Meta("systemProgram", inst.AccountMetaSlice.Get(5)))
						accountsBranch.Child(ag_format.Meta(" tokenProgram", inst.AccountMetaSlice.Get(6)))
						accountsBranch.Child(ag_format.Meta("        owner", inst.AccountMetaSlice.Get(7)))
						accountsBranch.Child(ag_format.Meta("       escrow", inst.AccountMetaSlice.Get(8)))
						accountsBranch.Child(ag_format.Meta(" programState", inst.AccountMetaSlice.Get(9)))
						accountsBranch.Child(ag_format.Meta("         mint", inst.AccountMetaSlice.Get(10)))
					})
				})
		})
}

func (obj LeaseInit) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	// Serialize `Params` param:
	err = encoder.Encode(obj.Params)
	if err != nil {
		return err
	}
	return nil
}
func (obj *LeaseInit) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	// Deserialize `Params`:
	err = decoder.Decode(&obj.Params)
	if err != nil {
		return err
	}
	return nil
}

// NewLeaseInitInstruction declares a new LeaseInit instruction with the provided parameters and accounts.
func NewLeaseInitInstruction(
	// Parameters:
	params LeaseInitParams,
	// Accounts:
	lease ag_solanago.PublicKey,
	queue ag_solanago.PublicKey,
	aggregator ag_solanago.PublicKey,
	funder ag_solanago.PublicKey,
	payer ag_solanago.PublicKey,
	systemProgram ag_solanago.PublicKey,
	tokenProgram ag_solanago.PublicKey,
	owner ag_solanago.PublicKey,
	escrow ag_solanago.PublicKey,
	programState ag_solanago.PublicKey,
	mint ag_solanago.PublicKey) *LeaseInit {
	return NewLeaseInitInstructionBuilder().
		SetParams(params).
		SetLeaseAccount(lease).
		SetQueueAccount(queue).
		SetAggregatorAccount(aggregator).
		SetFunderAccount(funder).
		SetPayerAccount(payer).
		SetSystemProgramAccount(systemProgram).
		SetTokenProgramAccount(tokenProgram).
		SetOwnerAccount(owner).
		SetEscrowAccount(escrow).
		SetProgramStateAccount(programState).
		SetMintAccount(mint)
}
