// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.

package switchboard_v2

import (
	"errors"
	ag_binary "github.com/gagliardetto/binary"
	ag_solanago "github.com/gagliardetto/solana-go"
	ag_format "github.com/gagliardetto/solana-go/text/format"
	ag_treeout "github.com/gagliardetto/treeout"
)

// LeaseExtend is the `leaseExtend` instruction.
type LeaseExtend struct {
	Params *LeaseExtendParams

	// [0] = [WRITE] lease
	//
	// [1] = [] aggregator
	//
	// [2] = [] queue
	//
	// [3] = [WRITE] funder
	//
	// [4] = [WRITE, SIGNER] owner
	//
	// [5] = [WRITE] escrow
	//
	// [6] = [] tokenProgram
	//
	// [7] = [] programState
	//
	// [8] = [] mint
	ag_solanago.AccountMetaSlice `bin:"-"`
}

// NewLeaseExtendInstructionBuilder creates a new `LeaseExtend` instruction builder.
func NewLeaseExtendInstructionBuilder() *LeaseExtend {
	nd := &LeaseExtend{
		AccountMetaSlice: make(ag_solanago.AccountMetaSlice, 9),
	}
	return nd
}

// SetParams sets the "params" parameter.
func (inst *LeaseExtend) SetParams(params LeaseExtendParams) *LeaseExtend {
	inst.Params = &params
	return inst
}

// SetLeaseAccount sets the "lease" account.
func (inst *LeaseExtend) SetLeaseAccount(lease ag_solanago.PublicKey) *LeaseExtend {
	inst.AccountMetaSlice[0] = ag_solanago.Meta(lease).WRITE()
	return inst
}

// GetLeaseAccount gets the "lease" account.
func (inst *LeaseExtend) GetLeaseAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(0)
}

// SetAggregatorAccount sets the "aggregator" account.
func (inst *LeaseExtend) SetAggregatorAccount(aggregator ag_solanago.PublicKey) *LeaseExtend {
	inst.AccountMetaSlice[1] = ag_solanago.Meta(aggregator)
	return inst
}

// GetAggregatorAccount gets the "aggregator" account.
func (inst *LeaseExtend) GetAggregatorAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(1)
}

// SetQueueAccount sets the "queue" account.
func (inst *LeaseExtend) SetQueueAccount(queue ag_solanago.PublicKey) *LeaseExtend {
	inst.AccountMetaSlice[2] = ag_solanago.Meta(queue)
	return inst
}

// GetQueueAccount gets the "queue" account.
func (inst *LeaseExtend) GetQueueAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(2)
}

// SetFunderAccount sets the "funder" account.
func (inst *LeaseExtend) SetFunderAccount(funder ag_solanago.PublicKey) *LeaseExtend {
	inst.AccountMetaSlice[3] = ag_solanago.Meta(funder).WRITE()
	return inst
}

// GetFunderAccount gets the "funder" account.
func (inst *LeaseExtend) GetFunderAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(3)
}

// SetOwnerAccount sets the "owner" account.
func (inst *LeaseExtend) SetOwnerAccount(owner ag_solanago.PublicKey) *LeaseExtend {
	inst.AccountMetaSlice[4] = ag_solanago.Meta(owner).WRITE().SIGNER()
	return inst
}

// GetOwnerAccount gets the "owner" account.
func (inst *LeaseExtend) GetOwnerAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(4)
}

// SetEscrowAccount sets the "escrow" account.
func (inst *LeaseExtend) SetEscrowAccount(escrow ag_solanago.PublicKey) *LeaseExtend {
	inst.AccountMetaSlice[5] = ag_solanago.Meta(escrow).WRITE()
	return inst
}

// GetEscrowAccount gets the "escrow" account.
func (inst *LeaseExtend) GetEscrowAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(5)
}

// SetTokenProgramAccount sets the "tokenProgram" account.
func (inst *LeaseExtend) SetTokenProgramAccount(tokenProgram ag_solanago.PublicKey) *LeaseExtend {
	inst.AccountMetaSlice[6] = ag_solanago.Meta(tokenProgram)
	return inst
}

// GetTokenProgramAccount gets the "tokenProgram" account.
func (inst *LeaseExtend) GetTokenProgramAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(6)
}

// SetProgramStateAccount sets the "programState" account.
func (inst *LeaseExtend) SetProgramStateAccount(programState ag_solanago.PublicKey) *LeaseExtend {
	inst.AccountMetaSlice[7] = ag_solanago.Meta(programState)
	return inst
}

// GetProgramStateAccount gets the "programState" account.
func (inst *LeaseExtend) GetProgramStateAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(7)
}

// SetMintAccount sets the "mint" account.
func (inst *LeaseExtend) SetMintAccount(mint ag_solanago.PublicKey) *LeaseExtend {
	inst.AccountMetaSlice[8] = ag_solanago.Meta(mint)
	return inst
}

// GetMintAccount gets the "mint" account.
func (inst *LeaseExtend) GetMintAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(8)
}

func (inst LeaseExtend) Build() *Instruction {
	return &Instruction{BaseVariant: ag_binary.BaseVariant{
		Impl:   inst,
		TypeID: Instruction_LeaseExtend,
	}}
}

// ValidateAndBuild validates the instruction parameters and accounts;
// if there is a validation error, it returns the error.
// Otherwise, it builds and returns the instruction.
func (inst LeaseExtend) ValidateAndBuild() (*Instruction, error) {
	if err := inst.Validate(); err != nil {
		return nil, err
	}
	return inst.Build(), nil
}

func (inst *LeaseExtend) Validate() error {
	// Check whether all (required) parameters are set:
	{
		if inst.Params == nil {
			return errors.New("Params parameter is not set")
		}
	}

	// Check whether all (required) accounts are set:
	{
		if inst.AccountMetaSlice[0] == nil {
			return errors.New("accounts.Lease is not set")
		}
		if inst.AccountMetaSlice[1] == nil {
			return errors.New("accounts.Aggregator is not set")
		}
		if inst.AccountMetaSlice[2] == nil {
			return errors.New("accounts.Queue is not set")
		}
		if inst.AccountMetaSlice[3] == nil {
			return errors.New("accounts.Funder is not set")
		}
		if inst.AccountMetaSlice[4] == nil {
			return errors.New("accounts.Owner is not set")
		}
		if inst.AccountMetaSlice[5] == nil {
			return errors.New("accounts.Escrow is not set")
		}
		if inst.AccountMetaSlice[6] == nil {
			return errors.New("accounts.TokenProgram is not set")
		}
		if inst.AccountMetaSlice[7] == nil {
			return errors.New("accounts.ProgramState is not set")
		}
		if inst.AccountMetaSlice[8] == nil {
			return errors.New("accounts.Mint is not set")
		}
	}
	return nil
}

func (inst *LeaseExtend) EncodeToTree(parent ag_treeout.Branches) {
	parent.Child(ag_format.Program(ProgramName, ProgramID)).
		//
		ParentFunc(func(programBranch ag_treeout.Branches) {
			programBranch.Child(ag_format.Instruction("LeaseExtend")).
				//
				ParentFunc(func(instructionBranch ag_treeout.Branches) {

					// Parameters of the instruction:
					instructionBranch.Child("Params[len=1]").ParentFunc(func(paramsBranch ag_treeout.Branches) {
						paramsBranch.Child(ag_format.Param("Params", *inst.Params))
					})

					// Accounts of the instruction:
					instructionBranch.Child("Accounts[len=9]").ParentFunc(func(accountsBranch ag_treeout.Branches) {
						accountsBranch.Child(ag_format.Meta("       lease", inst.AccountMetaSlice.Get(0)))
						accountsBranch.Child(ag_format.Meta("  aggregator", inst.AccountMetaSlice.Get(1)))
						accountsBranch.Child(ag_format.Meta("       queue", inst.AccountMetaSlice.Get(2)))
						accountsBranch.Child(ag_format.Meta("      funder", inst.AccountMetaSlice.Get(3)))
						accountsBranch.Child(ag_format.Meta("       owner", inst.AccountMetaSlice.Get(4)))
						accountsBranch.Child(ag_format.Meta("      escrow", inst.AccountMetaSlice.Get(5)))
						accountsBranch.Child(ag_format.Meta("tokenProgram", inst.AccountMetaSlice.Get(6)))
						accountsBranch.Child(ag_format.Meta("programState", inst.AccountMetaSlice.Get(7)))
						accountsBranch.Child(ag_format.Meta("        mint", inst.AccountMetaSlice.Get(8)))
					})
				})
		})
}

func (obj LeaseExtend) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	// Serialize `Params` param:
	err = encoder.Encode(obj.Params)
	if err != nil {
		return err
	}
	return nil
}
func (obj *LeaseExtend) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	// Deserialize `Params`:
	err = decoder.Decode(&obj.Params)
	if err != nil {
		return err
	}
	return nil
}

// NewLeaseExtendInstruction declares a new LeaseExtend instruction with the provided parameters and accounts.
func NewLeaseExtendInstruction(
	// Parameters:
	params LeaseExtendParams,
	// Accounts:
	lease ag_solanago.PublicKey,
	aggregator ag_solanago.PublicKey,
	queue ag_solanago.PublicKey,
	funder ag_solanago.PublicKey,
	owner ag_solanago.PublicKey,
	escrow ag_solanago.PublicKey,
	tokenProgram ag_solanago.PublicKey,
	programState ag_solanago.PublicKey,
	mint ag_solanago.PublicKey) *LeaseExtend {
	return NewLeaseExtendInstructionBuilder().
		SetParams(params).
		SetLeaseAccount(lease).
		SetAggregatorAccount(aggregator).
		SetQueueAccount(queue).
		SetFunderAccount(funder).
		SetOwnerAccount(owner).
		SetEscrowAccount(escrow).
		SetTokenProgramAccount(tokenProgram).
		SetProgramStateAccount(programState).
		SetMintAccount(mint)
}
