// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.

package switchboard_v2

import (
	"errors"
	ag_binary "github.com/gagliardetto/binary"
	ag_solanago "github.com/gagliardetto/solana-go"
	ag_format "github.com/gagliardetto/solana-go/text/format"
	ag_treeout "github.com/gagliardetto/treeout"
)

// OracleQueueInit is the `oracleQueueInit` instruction.
type OracleQueueInit struct {
	Params *OracleQueueInitParams

	// [0] = [WRITE, SIGNER] oracleQueue
	//
	// [1] = [] authority
	//
	// [2] = [WRITE] buffer
	//
	// [3] = [WRITE, SIGNER] payer
	//
	// [4] = [] systemProgram
	//
	// [5] = [] mint
	ag_solanago.AccountMetaSlice `bin:"-"`
}

// NewOracleQueueInitInstructionBuilder creates a new `OracleQueueInit` instruction builder.
func NewOracleQueueInitInstructionBuilder() *OracleQueueInit {
	nd := &OracleQueueInit{
		AccountMetaSlice: make(ag_solanago.AccountMetaSlice, 6),
	}
	return nd
}

// SetParams sets the "params" parameter.
func (inst *OracleQueueInit) SetParams(params OracleQueueInitParams) *OracleQueueInit {
	inst.Params = &params
	return inst
}

// SetOracleQueueAccount sets the "oracleQueue" account.
func (inst *OracleQueueInit) SetOracleQueueAccount(oracleQueue ag_solanago.PublicKey) *OracleQueueInit {
	inst.AccountMetaSlice[0] = ag_solanago.Meta(oracleQueue).WRITE().SIGNER()
	return inst
}

// GetOracleQueueAccount gets the "oracleQueue" account.
func (inst *OracleQueueInit) GetOracleQueueAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(0)
}

// SetAuthorityAccount sets the "authority" account.
func (inst *OracleQueueInit) SetAuthorityAccount(authority ag_solanago.PublicKey) *OracleQueueInit {
	inst.AccountMetaSlice[1] = ag_solanago.Meta(authority)
	return inst
}

// GetAuthorityAccount gets the "authority" account.
func (inst *OracleQueueInit) GetAuthorityAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(1)
}

// SetBufferAccount sets the "buffer" account.
func (inst *OracleQueueInit) SetBufferAccount(buffer ag_solanago.PublicKey) *OracleQueueInit {
	inst.AccountMetaSlice[2] = ag_solanago.Meta(buffer).WRITE()
	return inst
}

// GetBufferAccount gets the "buffer" account.
func (inst *OracleQueueInit) GetBufferAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(2)
}

// SetPayerAccount sets the "payer" account.
func (inst *OracleQueueInit) SetPayerAccount(payer ag_solanago.PublicKey) *OracleQueueInit {
	inst.AccountMetaSlice[3] = ag_solanago.Meta(payer).WRITE().SIGNER()
	return inst
}

// GetPayerAccount gets the "payer" account.
func (inst *OracleQueueInit) GetPayerAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(3)
}

// SetSystemProgramAccount sets the "systemProgram" account.
func (inst *OracleQueueInit) SetSystemProgramAccount(systemProgram ag_solanago.PublicKey) *OracleQueueInit {
	inst.AccountMetaSlice[4] = ag_solanago.Meta(systemProgram)
	return inst
}

// GetSystemProgramAccount gets the "systemProgram" account.
func (inst *OracleQueueInit) GetSystemProgramAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(4)
}

// SetMintAccount sets the "mint" account.
func (inst *OracleQueueInit) SetMintAccount(mint ag_solanago.PublicKey) *OracleQueueInit {
	inst.AccountMetaSlice[5] = ag_solanago.Meta(mint)
	return inst
}

// GetMintAccount gets the "mint" account.
func (inst *OracleQueueInit) GetMintAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(5)
}

func (inst OracleQueueInit) Build() *Instruction {
	return &Instruction{BaseVariant: ag_binary.BaseVariant{
		Impl:   inst,
		TypeID: Instruction_OracleQueueInit,
	}}
}

// ValidateAndBuild validates the instruction parameters and accounts;
// if there is a validation error, it returns the error.
// Otherwise, it builds and returns the instruction.
func (inst OracleQueueInit) ValidateAndBuild() (*Instruction, error) {
	if err := inst.Validate(); err != nil {
		return nil, err
	}
	return inst.Build(), nil
}

func (inst *OracleQueueInit) Validate() error {
	// Check whether all (required) parameters are set:
	{
		if inst.Params == nil {
			return errors.New("Params parameter is not set")
		}
	}

	// Check whether all (required) accounts are set:
	{
		if inst.AccountMetaSlice[0] == nil {
			return errors.New("accounts.OracleQueue is not set")
		}
		if inst.AccountMetaSlice[1] == nil {
			return errors.New("accounts.Authority is not set")
		}
		if inst.AccountMetaSlice[2] == nil {
			return errors.New("accounts.Buffer is not set")
		}
		if inst.AccountMetaSlice[3] == nil {
			return errors.New("accounts.Payer is not set")
		}
		if inst.AccountMetaSlice[4] == nil {
			return errors.New("accounts.SystemProgram is not set")
		}
		if inst.AccountMetaSlice[5] == nil {
			return errors.New("accounts.Mint is not set")
		}
	}
	return nil
}

func (inst *OracleQueueInit) EncodeToTree(parent ag_treeout.Branches) {
	parent.Child(ag_format.Program(ProgramName, ProgramID)).
		//
		ParentFunc(func(programBranch ag_treeout.Branches) {
			programBranch.Child(ag_format.Instruction("OracleQueueInit")).
				//
				ParentFunc(func(instructionBranch ag_treeout.Branches) {

					// Parameters of the instruction:
					instructionBranch.Child("Params[len=1]").ParentFunc(func(paramsBranch ag_treeout.Branches) {
						paramsBranch.Child(ag_format.Param("Params", *inst.Params))
					})

					// Accounts of the instruction:
					instructionBranch.Child("Accounts[len=6]").ParentFunc(func(accountsBranch ag_treeout.Branches) {
						accountsBranch.Child(ag_format.Meta("  oracleQueue", inst.AccountMetaSlice.Get(0)))
						accountsBranch.Child(ag_format.Meta("    authority", inst.AccountMetaSlice.Get(1)))
						accountsBranch.Child(ag_format.Meta("       buffer", inst.AccountMetaSlice.Get(2)))
						accountsBranch.Child(ag_format.Meta("        payer", inst.AccountMetaSlice.Get(3)))
						accountsBranch.Child(ag_format.Meta("systemProgram", inst.AccountMetaSlice.Get(4)))
						accountsBranch.Child(ag_format.Meta("         mint", inst.AccountMetaSlice.Get(5)))
					})
				})
		})
}

func (obj OracleQueueInit) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	// Serialize `Params` param:
	err = encoder.Encode(obj.Params)
	if err != nil {
		return err
	}
	return nil
}
func (obj *OracleQueueInit) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	// Deserialize `Params`:
	err = decoder.Decode(&obj.Params)
	if err != nil {
		return err
	}
	return nil
}

// NewOracleQueueInitInstruction declares a new OracleQueueInit instruction with the provided parameters and accounts.
func NewOracleQueueInitInstruction(
	// Parameters:
	params OracleQueueInitParams,
	// Accounts:
	oracleQueue ag_solanago.PublicKey,
	authority ag_solanago.PublicKey,
	buffer ag_solanago.PublicKey,
	payer ag_solanago.PublicKey,
	systemProgram ag_solanago.PublicKey,
	mint ag_solanago.PublicKey) *OracleQueueInit {
	return NewOracleQueueInitInstructionBuilder().
		SetParams(params).
		SetOracleQueueAccount(oracleQueue).
		SetAuthorityAccount(authority).
		SetBufferAccount(buffer).
		SetPayerAccount(payer).
		SetSystemProgramAccount(systemProgram).
		SetMintAccount(mint)
}
