// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.

package switchboard_v2

import (
	"errors"
	ag_binary "github.com/gagliardetto/binary"
	ag_solanago "github.com/gagliardetto/solana-go"
	ag_format "github.com/gagliardetto/solana-go/text/format"
	ag_treeout "github.com/gagliardetto/treeout"
)

// OracleQueueSetConfig is the `oracleQueueSetConfig` instruction.
type OracleQueueSetConfig struct {
	Params *OracleQueueSetConfigParams

	// [0] = [WRITE] queue
	//
	// [1] = [SIGNER] authority
	ag_solanago.AccountMetaSlice `bin:"-"`
}

// NewOracleQueueSetConfigInstructionBuilder creates a new `OracleQueueSetConfig` instruction builder.
func NewOracleQueueSetConfigInstructionBuilder() *OracleQueueSetConfig {
	nd := &OracleQueueSetConfig{
		AccountMetaSlice: make(ag_solanago.AccountMetaSlice, 2),
	}
	return nd
}

// SetParams sets the "params" parameter.
func (inst *OracleQueueSetConfig) SetParams(params OracleQueueSetConfigParams) *OracleQueueSetConfig {
	inst.Params = &params
	return inst
}

// SetQueueAccount sets the "queue" account.
func (inst *OracleQueueSetConfig) SetQueueAccount(queue ag_solanago.PublicKey) *OracleQueueSetConfig {
	inst.AccountMetaSlice[0] = ag_solanago.Meta(queue).WRITE()
	return inst
}

// GetQueueAccount gets the "queue" account.
func (inst *OracleQueueSetConfig) GetQueueAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(0)
}

// SetAuthorityAccount sets the "authority" account.
func (inst *OracleQueueSetConfig) SetAuthorityAccount(authority ag_solanago.PublicKey) *OracleQueueSetConfig {
	inst.AccountMetaSlice[1] = ag_solanago.Meta(authority).SIGNER()
	return inst
}

// GetAuthorityAccount gets the "authority" account.
func (inst *OracleQueueSetConfig) GetAuthorityAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(1)
}

func (inst OracleQueueSetConfig) Build() *Instruction {
	return &Instruction{BaseVariant: ag_binary.BaseVariant{
		Impl:   inst,
		TypeID: Instruction_OracleQueueSetConfig,
	}}
}

// ValidateAndBuild validates the instruction parameters and accounts;
// if there is a validation error, it returns the error.
// Otherwise, it builds and returns the instruction.
func (inst OracleQueueSetConfig) ValidateAndBuild() (*Instruction, error) {
	if err := inst.Validate(); err != nil {
		return nil, err
	}
	return inst.Build(), nil
}

func (inst *OracleQueueSetConfig) Validate() error {
	// Check whether all (required) parameters are set:
	{
		if inst.Params == nil {
			return errors.New("Params parameter is not set")
		}
	}

	// Check whether all (required) accounts are set:
	{
		if inst.AccountMetaSlice[0] == nil {
			return errors.New("accounts.Queue is not set")
		}
		if inst.AccountMetaSlice[1] == nil {
			return errors.New("accounts.Authority is not set")
		}
	}
	return nil
}

func (inst *OracleQueueSetConfig) EncodeToTree(parent ag_treeout.Branches) {
	parent.Child(ag_format.Program(ProgramName, ProgramID)).
		//
		ParentFunc(func(programBranch ag_treeout.Branches) {
			programBranch.Child(ag_format.Instruction("OracleQueueSetConfig")).
				//
				ParentFunc(func(instructionBranch ag_treeout.Branches) {

					// Parameters of the instruction:
					instructionBranch.Child("Params[len=1]").ParentFunc(func(paramsBranch ag_treeout.Branches) {
						paramsBranch.Child(ag_format.Param("Params", *inst.Params))
					})

					// Accounts of the instruction:
					instructionBranch.Child("Accounts[len=2]").ParentFunc(func(accountsBranch ag_treeout.Branches) {
						accountsBranch.Child(ag_format.Meta("    queue", inst.AccountMetaSlice.Get(0)))
						accountsBranch.Child(ag_format.Meta("authority", inst.AccountMetaSlice.Get(1)))
					})
				})
		})
}

func (obj OracleQueueSetConfig) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	// Serialize `Params` param:
	err = encoder.Encode(obj.Params)
	if err != nil {
		return err
	}
	return nil
}
func (obj *OracleQueueSetConfig) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	// Deserialize `Params`:
	err = decoder.Decode(&obj.Params)
	if err != nil {
		return err
	}
	return nil
}

// NewOracleQueueSetConfigInstruction declares a new OracleQueueSetConfig instruction with the provided parameters and accounts.
func NewOracleQueueSetConfigInstruction(
	// Parameters:
	params OracleQueueSetConfigParams,
	// Accounts:
	queue ag_solanago.PublicKey,
	authority ag_solanago.PublicKey) *OracleQueueSetConfig {
	return NewOracleQueueSetConfigInstructionBuilder().
		SetParams(params).
		SetQueueAccount(queue).
		SetAuthorityAccount(authority)
}
