// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.

package switchboard_v2

import (
	"errors"
	ag_binary "github.com/gagliardetto/binary"
	ag_solanago "github.com/gagliardetto/solana-go"
	ag_format "github.com/gagliardetto/solana-go/text/format"
	ag_treeout "github.com/gagliardetto/treeout"
)

// PermissionSet is the `permissionSet` instruction.
type PermissionSet struct {
	Params *PermissionSetParams

	// [0] = [WRITE] permission
	//
	// [1] = [SIGNER] authority
	ag_solanago.AccountMetaSlice `bin:"-"`
}

// NewPermissionSetInstructionBuilder creates a new `PermissionSet` instruction builder.
func NewPermissionSetInstructionBuilder() *PermissionSet {
	nd := &PermissionSet{
		AccountMetaSlice: make(ag_solanago.AccountMetaSlice, 2),
	}
	return nd
}

// SetParams sets the "params" parameter.
func (inst *PermissionSet) SetParams(params PermissionSetParams) *PermissionSet {
	inst.Params = &params
	return inst
}

// SetPermissionAccount sets the "permission" account.
func (inst *PermissionSet) SetPermissionAccount(permission ag_solanago.PublicKey) *PermissionSet {
	inst.AccountMetaSlice[0] = ag_solanago.Meta(permission).WRITE()
	return inst
}

// GetPermissionAccount gets the "permission" account.
func (inst *PermissionSet) GetPermissionAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(0)
}

// SetAuthorityAccount sets the "authority" account.
func (inst *PermissionSet) SetAuthorityAccount(authority ag_solanago.PublicKey) *PermissionSet {
	inst.AccountMetaSlice[1] = ag_solanago.Meta(authority).SIGNER()
	return inst
}

// GetAuthorityAccount gets the "authority" account.
func (inst *PermissionSet) GetAuthorityAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(1)
}

func (inst PermissionSet) Build() *Instruction {
	return &Instruction{BaseVariant: ag_binary.BaseVariant{
		Impl:   inst,
		TypeID: Instruction_PermissionSet,
	}}
}

// ValidateAndBuild validates the instruction parameters and accounts;
// if there is a validation error, it returns the error.
// Otherwise, it builds and returns the instruction.
func (inst PermissionSet) ValidateAndBuild() (*Instruction, error) {
	if err := inst.Validate(); err != nil {
		return nil, err
	}
	return inst.Build(), nil
}

func (inst *PermissionSet) Validate() error {
	// Check whether all (required) parameters are set:
	{
		if inst.Params == nil {
			return errors.New("Params parameter is not set")
		}
	}

	// Check whether all (required) accounts are set:
	{
		if inst.AccountMetaSlice[0] == nil {
			return errors.New("accounts.Permission is not set")
		}
		if inst.AccountMetaSlice[1] == nil {
			return errors.New("accounts.Authority is not set")
		}
	}
	return nil
}

func (inst *PermissionSet) EncodeToTree(parent ag_treeout.Branches) {
	parent.Child(ag_format.Program(ProgramName, ProgramID)).
		//
		ParentFunc(func(programBranch ag_treeout.Branches) {
			programBranch.Child(ag_format.Instruction("PermissionSet")).
				//
				ParentFunc(func(instructionBranch ag_treeout.Branches) {

					// Parameters of the instruction:
					instructionBranch.Child("Params[len=1]").ParentFunc(func(paramsBranch ag_treeout.Branches) {
						paramsBranch.Child(ag_format.Param("Params", *inst.Params))
					})

					// Accounts of the instruction:
					instructionBranch.Child("Accounts[len=2]").ParentFunc(func(accountsBranch ag_treeout.Branches) {
						accountsBranch.Child(ag_format.Meta("permission", inst.AccountMetaSlice.Get(0)))
						accountsBranch.Child(ag_format.Meta(" authority", inst.AccountMetaSlice.Get(1)))
					})
				})
		})
}

func (obj PermissionSet) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	// Serialize `Params` param:
	err = encoder.Encode(obj.Params)
	if err != nil {
		return err
	}
	return nil
}
func (obj *PermissionSet) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	// Deserialize `Params`:
	err = decoder.Decode(&obj.Params)
	if err != nil {
		return err
	}
	return nil
}

// NewPermissionSetInstruction declares a new PermissionSet instruction with the provided parameters and accounts.
func NewPermissionSetInstruction(
	// Parameters:
	params PermissionSetParams,
	// Accounts:
	permission ag_solanago.PublicKey,
	authority ag_solanago.PublicKey) *PermissionSet {
	return NewPermissionSetInstructionBuilder().
		SetParams(params).
		SetPermissionAccount(permission).
		SetAuthorityAccount(authority)
}
