// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.

package switchboard_v2

import (
	"errors"
	ag_binary "github.com/gagliardetto/binary"
	ag_solanago "github.com/gagliardetto/solana-go"
	ag_format "github.com/gagliardetto/solana-go/text/format"
	ag_treeout "github.com/gagliardetto/treeout"
)

// VrfLiteCloseAction is the `vrfLiteCloseAction` instruction.
type VrfLiteCloseAction struct {
	Params *VrfLiteCloseParams

	// [0] = [SIGNER] authority
	//
	// [1] = [WRITE] vrfLite
	//
	// [2] = [WRITE] permission
	//
	// [3] = [] queue
	//
	// [4] = [] queueAuthority
	//
	// [5] = [] programState
	//
	// [6] = [WRITE] escrow
	//
	// [7] = [] solDest
	//
	// [8] = [WRITE] escrowDest
	//
	// [9] = [] tokenProgram
	ag_solanago.AccountMetaSlice `bin:"-"`
}

// NewVrfLiteCloseActionInstructionBuilder creates a new `VrfLiteCloseAction` instruction builder.
func NewVrfLiteCloseActionInstructionBuilder() *VrfLiteCloseAction {
	nd := &VrfLiteCloseAction{
		AccountMetaSlice: make(ag_solanago.AccountMetaSlice, 10),
	}
	return nd
}

// SetParams sets the "params" parameter.
func (inst *VrfLiteCloseAction) SetParams(params VrfLiteCloseParams) *VrfLiteCloseAction {
	inst.Params = &params
	return inst
}

// SetAuthorityAccount sets the "authority" account.
func (inst *VrfLiteCloseAction) SetAuthorityAccount(authority ag_solanago.PublicKey) *VrfLiteCloseAction {
	inst.AccountMetaSlice[0] = ag_solanago.Meta(authority).SIGNER()
	return inst
}

// GetAuthorityAccount gets the "authority" account.
func (inst *VrfLiteCloseAction) GetAuthorityAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(0)
}

// SetVrfLiteAccount sets the "vrfLite" account.
func (inst *VrfLiteCloseAction) SetVrfLiteAccount(vrfLite ag_solanago.PublicKey) *VrfLiteCloseAction {
	inst.AccountMetaSlice[1] = ag_solanago.Meta(vrfLite).WRITE()
	return inst
}

// GetVrfLiteAccount gets the "vrfLite" account.
func (inst *VrfLiteCloseAction) GetVrfLiteAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(1)
}

// SetPermissionAccount sets the "permission" account.
func (inst *VrfLiteCloseAction) SetPermissionAccount(permission ag_solanago.PublicKey) *VrfLiteCloseAction {
	inst.AccountMetaSlice[2] = ag_solanago.Meta(permission).WRITE()
	return inst
}

// GetPermissionAccount gets the "permission" account.
func (inst *VrfLiteCloseAction) GetPermissionAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(2)
}

// SetQueueAccount sets the "queue" account.
func (inst *VrfLiteCloseAction) SetQueueAccount(queue ag_solanago.PublicKey) *VrfLiteCloseAction {
	inst.AccountMetaSlice[3] = ag_solanago.Meta(queue)
	return inst
}

// GetQueueAccount gets the "queue" account.
func (inst *VrfLiteCloseAction) GetQueueAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(3)
}

// SetQueueAuthorityAccount sets the "queueAuthority" account.
func (inst *VrfLiteCloseAction) SetQueueAuthorityAccount(queueAuthority ag_solanago.PublicKey) *VrfLiteCloseAction {
	inst.AccountMetaSlice[4] = ag_solanago.Meta(queueAuthority)
	return inst
}

// GetQueueAuthorityAccount gets the "queueAuthority" account.
func (inst *VrfLiteCloseAction) GetQueueAuthorityAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(4)
}

// SetProgramStateAccount sets the "programState" account.
func (inst *VrfLiteCloseAction) SetProgramStateAccount(programState ag_solanago.PublicKey) *VrfLiteCloseAction {
	inst.AccountMetaSlice[5] = ag_solanago.Meta(programState)
	return inst
}

// GetProgramStateAccount gets the "programState" account.
func (inst *VrfLiteCloseAction) GetProgramStateAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(5)
}

// SetEscrowAccount sets the "escrow" account.
func (inst *VrfLiteCloseAction) SetEscrowAccount(escrow ag_solanago.PublicKey) *VrfLiteCloseAction {
	inst.AccountMetaSlice[6] = ag_solanago.Meta(escrow).WRITE()
	return inst
}

// GetEscrowAccount gets the "escrow" account.
func (inst *VrfLiteCloseAction) GetEscrowAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(6)
}

// SetSolDestAccount sets the "solDest" account.
func (inst *VrfLiteCloseAction) SetSolDestAccount(solDest ag_solanago.PublicKey) *VrfLiteCloseAction {
	inst.AccountMetaSlice[7] = ag_solanago.Meta(solDest)
	return inst
}

// GetSolDestAccount gets the "solDest" account.
func (inst *VrfLiteCloseAction) GetSolDestAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(7)
}

// SetEscrowDestAccount sets the "escrowDest" account.
func (inst *VrfLiteCloseAction) SetEscrowDestAccount(escrowDest ag_solanago.PublicKey) *VrfLiteCloseAction {
	inst.AccountMetaSlice[8] = ag_solanago.Meta(escrowDest).WRITE()
	return inst
}

// GetEscrowDestAccount gets the "escrowDest" account.
func (inst *VrfLiteCloseAction) GetEscrowDestAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(8)
}

// SetTokenProgramAccount sets the "tokenProgram" account.
func (inst *VrfLiteCloseAction) SetTokenProgramAccount(tokenProgram ag_solanago.PublicKey) *VrfLiteCloseAction {
	inst.AccountMetaSlice[9] = ag_solanago.Meta(tokenProgram)
	return inst
}

// GetTokenProgramAccount gets the "tokenProgram" account.
func (inst *VrfLiteCloseAction) GetTokenProgramAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(9)
}

func (inst VrfLiteCloseAction) Build() *Instruction {
	return &Instruction{BaseVariant: ag_binary.BaseVariant{
		Impl:   inst,
		TypeID: Instruction_VrfLiteCloseAction,
	}}
}

// ValidateAndBuild validates the instruction parameters and accounts;
// if there is a validation error, it returns the error.
// Otherwise, it builds and returns the instruction.
func (inst VrfLiteCloseAction) ValidateAndBuild() (*Instruction, error) {
	if err := inst.Validate(); err != nil {
		return nil, err
	}
	return inst.Build(), nil
}

func (inst *VrfLiteCloseAction) Validate() error {
	// Check whether all (required) parameters are set:
	{
		if inst.Params == nil {
			return errors.New("Params parameter is not set")
		}
	}

	// Check whether all (required) accounts are set:
	{
		if inst.AccountMetaSlice[0] == nil {
			return errors.New("accounts.Authority is not set")
		}
		if inst.AccountMetaSlice[1] == nil {
			return errors.New("accounts.VrfLite is not set")
		}
		if inst.AccountMetaSlice[2] == nil {
			return errors.New("accounts.Permission is not set")
		}
		if inst.AccountMetaSlice[3] == nil {
			return errors.New("accounts.Queue is not set")
		}
		if inst.AccountMetaSlice[4] == nil {
			return errors.New("accounts.QueueAuthority is not set")
		}
		if inst.AccountMetaSlice[5] == nil {
			return errors.New("accounts.ProgramState is not set")
		}
		if inst.AccountMetaSlice[6] == nil {
			return errors.New("accounts.Escrow is not set")
		}
		if inst.AccountMetaSlice[7] == nil {
			return errors.New("accounts.SolDest is not set")
		}
		if inst.AccountMetaSlice[8] == nil {
			return errors.New("accounts.EscrowDest is not set")
		}
		if inst.AccountMetaSlice[9] == nil {
			return errors.New("accounts.TokenProgram is not set")
		}
	}
	return nil
}

func (inst *VrfLiteCloseAction) EncodeToTree(parent ag_treeout.Branches) {
	parent.Child(ag_format.Program(ProgramName, ProgramID)).
		//
		ParentFunc(func(programBranch ag_treeout.Branches) {
			programBranch.Child(ag_format.Instruction("VrfLiteCloseAction")).
				//
				ParentFunc(func(instructionBranch ag_treeout.Branches) {

					// Parameters of the instruction:
					instructionBranch.Child("Params[len=1]").ParentFunc(func(paramsBranch ag_treeout.Branches) {
						paramsBranch.Child(ag_format.Param("Params", *inst.Params))
					})

					// Accounts of the instruction:
					instructionBranch.Child("Accounts[len=10]").ParentFunc(func(accountsBranch ag_treeout.Branches) {
						accountsBranch.Child(ag_format.Meta("     authority", inst.AccountMetaSlice.Get(0)))
						accountsBranch.Child(ag_format.Meta("       vrfLite", inst.AccountMetaSlice.Get(1)))
						accountsBranch.Child(ag_format.Meta("    permission", inst.AccountMetaSlice.Get(2)))
						accountsBranch.Child(ag_format.Meta("         queue", inst.AccountMetaSlice.Get(3)))
						accountsBranch.Child(ag_format.Meta("queueAuthority", inst.AccountMetaSlice.Get(4)))
						accountsBranch.Child(ag_format.Meta("  programState", inst.AccountMetaSlice.Get(5)))
						accountsBranch.Child(ag_format.Meta("        escrow", inst.AccountMetaSlice.Get(6)))
						accountsBranch.Child(ag_format.Meta("       solDest", inst.AccountMetaSlice.Get(7)))
						accountsBranch.Child(ag_format.Meta("    escrowDest", inst.AccountMetaSlice.Get(8)))
						accountsBranch.Child(ag_format.Meta("  tokenProgram", inst.AccountMetaSlice.Get(9)))
					})
				})
		})
}

func (obj VrfLiteCloseAction) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	// Serialize `Params` param:
	err = encoder.Encode(obj.Params)
	if err != nil {
		return err
	}
	return nil
}
func (obj *VrfLiteCloseAction) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	// Deserialize `Params`:
	err = decoder.Decode(&obj.Params)
	if err != nil {
		return err
	}
	return nil
}

// NewVrfLiteCloseActionInstruction declares a new VrfLiteCloseAction instruction with the provided parameters and accounts.
func NewVrfLiteCloseActionInstruction(
	// Parameters:
	params VrfLiteCloseParams,
	// Accounts:
	authority ag_solanago.PublicKey,
	vrfLite ag_solanago.PublicKey,
	permission ag_solanago.PublicKey,
	queue ag_solanago.PublicKey,
	queueAuthority ag_solanago.PublicKey,
	programState ag_solanago.PublicKey,
	escrow ag_solanago.PublicKey,
	solDest ag_solanago.PublicKey,
	escrowDest ag_solanago.PublicKey,
	tokenProgram ag_solanago.PublicKey) *VrfLiteCloseAction {
	return NewVrfLiteCloseActionInstructionBuilder().
		SetParams(params).
		SetAuthorityAccount(authority).
		SetVrfLiteAccount(vrfLite).
		SetPermissionAccount(permission).
		SetQueueAccount(queue).
		SetQueueAuthorityAccount(queueAuthority).
		SetProgramStateAccount(programState).
		SetEscrowAccount(escrow).
		SetSolDestAccount(solDest).
		SetEscrowDestAccount(escrowDest).
		SetTokenProgramAccount(tokenProgram)
}
