// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.

package switchboard_v2

import (
	"errors"
	ag_binary "github.com/gagliardetto/binary"
	ag_solanago "github.com/gagliardetto/solana-go"
	ag_format "github.com/gagliardetto/solana-go/text/format"
	ag_treeout "github.com/gagliardetto/treeout"
)

// VrfLiteInit is the `vrfLiteInit` instruction.
type VrfLiteInit struct {
	Params *VrfLiteInitParams

	// [0] = [] authority
	//
	// [1] = [WRITE, SIGNER] vrf
	//
	// [2] = [] mint
	//
	// [3] = [WRITE] escrow
	//
	// [4] = [] queueAuthority
	//
	// [5] = [] queue
	//
	// [6] = [WRITE] permission
	//
	// [7] = [] programState
	//
	// [8] = [WRITE, SIGNER] payer
	//
	// [9] = [] tokenProgram
	//
	// [10] = [] associatedTokenProgram
	//
	// [11] = [] systemProgram
	//
	// [12] = [] rent
	ag_solanago.AccountMetaSlice `bin:"-"`
}

// NewVrfLiteInitInstructionBuilder creates a new `VrfLiteInit` instruction builder.
func NewVrfLiteInitInstructionBuilder() *VrfLiteInit {
	nd := &VrfLiteInit{
		AccountMetaSlice: make(ag_solanago.AccountMetaSlice, 13),
	}
	return nd
}

// SetParams sets the "params" parameter.
func (inst *VrfLiteInit) SetParams(params VrfLiteInitParams) *VrfLiteInit {
	inst.Params = &params
	return inst
}

// SetAuthorityAccount sets the "authority" account.
func (inst *VrfLiteInit) SetAuthorityAccount(authority ag_solanago.PublicKey) *VrfLiteInit {
	inst.AccountMetaSlice[0] = ag_solanago.Meta(authority)
	return inst
}

// GetAuthorityAccount gets the "authority" account.
func (inst *VrfLiteInit) GetAuthorityAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(0)
}

// SetVrfAccount sets the "vrf" account.
func (inst *VrfLiteInit) SetVrfAccount(vrf ag_solanago.PublicKey) *VrfLiteInit {
	inst.AccountMetaSlice[1] = ag_solanago.Meta(vrf).WRITE().SIGNER()
	return inst
}

// GetVrfAccount gets the "vrf" account.
func (inst *VrfLiteInit) GetVrfAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(1)
}

// SetMintAccount sets the "mint" account.
func (inst *VrfLiteInit) SetMintAccount(mint ag_solanago.PublicKey) *VrfLiteInit {
	inst.AccountMetaSlice[2] = ag_solanago.Meta(mint)
	return inst
}

// GetMintAccount gets the "mint" account.
func (inst *VrfLiteInit) GetMintAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(2)
}

// SetEscrowAccount sets the "escrow" account.
func (inst *VrfLiteInit) SetEscrowAccount(escrow ag_solanago.PublicKey) *VrfLiteInit {
	inst.AccountMetaSlice[3] = ag_solanago.Meta(escrow).WRITE()
	return inst
}

// GetEscrowAccount gets the "escrow" account.
func (inst *VrfLiteInit) GetEscrowAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(3)
}

// SetQueueAuthorityAccount sets the "queueAuthority" account.
func (inst *VrfLiteInit) SetQueueAuthorityAccount(queueAuthority ag_solanago.PublicKey) *VrfLiteInit {
	inst.AccountMetaSlice[4] = ag_solanago.Meta(queueAuthority)
	return inst
}

// GetQueueAuthorityAccount gets the "queueAuthority" account.
func (inst *VrfLiteInit) GetQueueAuthorityAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(4)
}

// SetQueueAccount sets the "queue" account.
func (inst *VrfLiteInit) SetQueueAccount(queue ag_solanago.PublicKey) *VrfLiteInit {
	inst.AccountMetaSlice[5] = ag_solanago.Meta(queue)
	return inst
}

// GetQueueAccount gets the "queue" account.
func (inst *VrfLiteInit) GetQueueAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(5)
}

// SetPermissionAccount sets the "permission" account.
func (inst *VrfLiteInit) SetPermissionAccount(permission ag_solanago.PublicKey) *VrfLiteInit {
	inst.AccountMetaSlice[6] = ag_solanago.Meta(permission).WRITE()
	return inst
}

// GetPermissionAccount gets the "permission" account.
func (inst *VrfLiteInit) GetPermissionAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(6)
}

// SetProgramStateAccount sets the "programState" account.
func (inst *VrfLiteInit) SetProgramStateAccount(programState ag_solanago.PublicKey) *VrfLiteInit {
	inst.AccountMetaSlice[7] = ag_solanago.Meta(programState)
	return inst
}

// GetProgramStateAccount gets the "programState" account.
func (inst *VrfLiteInit) GetProgramStateAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(7)
}

// SetPayerAccount sets the "payer" account.
func (inst *VrfLiteInit) SetPayerAccount(payer ag_solanago.PublicKey) *VrfLiteInit {
	inst.AccountMetaSlice[8] = ag_solanago.Meta(payer).WRITE().SIGNER()
	return inst
}

// GetPayerAccount gets the "payer" account.
func (inst *VrfLiteInit) GetPayerAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(8)
}

// SetTokenProgramAccount sets the "tokenProgram" account.
func (inst *VrfLiteInit) SetTokenProgramAccount(tokenProgram ag_solanago.PublicKey) *VrfLiteInit {
	inst.AccountMetaSlice[9] = ag_solanago.Meta(tokenProgram)
	return inst
}

// GetTokenProgramAccount gets the "tokenProgram" account.
func (inst *VrfLiteInit) GetTokenProgramAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(9)
}

// SetAssociatedTokenProgramAccount sets the "associatedTokenProgram" account.
func (inst *VrfLiteInit) SetAssociatedTokenProgramAccount(associatedTokenProgram ag_solanago.PublicKey) *VrfLiteInit {
	inst.AccountMetaSlice[10] = ag_solanago.Meta(associatedTokenProgram)
	return inst
}

// GetAssociatedTokenProgramAccount gets the "associatedTokenProgram" account.
func (inst *VrfLiteInit) GetAssociatedTokenProgramAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(10)
}

// SetSystemProgramAccount sets the "systemProgram" account.
func (inst *VrfLiteInit) SetSystemProgramAccount(systemProgram ag_solanago.PublicKey) *VrfLiteInit {
	inst.AccountMetaSlice[11] = ag_solanago.Meta(systemProgram)
	return inst
}

// GetSystemProgramAccount gets the "systemProgram" account.
func (inst *VrfLiteInit) GetSystemProgramAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(11)
}

// SetRentAccount sets the "rent" account.
func (inst *VrfLiteInit) SetRentAccount(rent ag_solanago.PublicKey) *VrfLiteInit {
	inst.AccountMetaSlice[12] = ag_solanago.Meta(rent)
	return inst
}

// GetRentAccount gets the "rent" account.
func (inst *VrfLiteInit) GetRentAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(12)
}

func (inst VrfLiteInit) Build() *Instruction {
	return &Instruction{BaseVariant: ag_binary.BaseVariant{
		Impl:   inst,
		TypeID: Instruction_VrfLiteInit,
	}}
}

// ValidateAndBuild validates the instruction parameters and accounts;
// if there is a validation error, it returns the error.
// Otherwise, it builds and returns the instruction.
func (inst VrfLiteInit) ValidateAndBuild() (*Instruction, error) {
	if err := inst.Validate(); err != nil {
		return nil, err
	}
	return inst.Build(), nil
}

func (inst *VrfLiteInit) Validate() error {
	// Check whether all (required) parameters are set:
	{
		if inst.Params == nil {
			return errors.New("Params parameter is not set")
		}
	}

	// Check whether all (required) accounts are set:
	{
		if inst.AccountMetaSlice[0] == nil {
			return errors.New("accounts.Authority is not set")
		}
		if inst.AccountMetaSlice[1] == nil {
			return errors.New("accounts.Vrf is not set")
		}
		if inst.AccountMetaSlice[2] == nil {
			return errors.New("accounts.Mint is not set")
		}
		if inst.AccountMetaSlice[3] == nil {
			return errors.New("accounts.Escrow is not set")
		}
		if inst.AccountMetaSlice[4] == nil {
			return errors.New("accounts.QueueAuthority is not set")
		}
		if inst.AccountMetaSlice[5] == nil {
			return errors.New("accounts.Queue is not set")
		}
		if inst.AccountMetaSlice[6] == nil {
			return errors.New("accounts.Permission is not set")
		}
		if inst.AccountMetaSlice[7] == nil {
			return errors.New("accounts.ProgramState is not set")
		}
		if inst.AccountMetaSlice[8] == nil {
			return errors.New("accounts.Payer is not set")
		}
		if inst.AccountMetaSlice[9] == nil {
			return errors.New("accounts.TokenProgram is not set")
		}
		if inst.AccountMetaSlice[10] == nil {
			return errors.New("accounts.AssociatedTokenProgram is not set")
		}
		if inst.AccountMetaSlice[11] == nil {
			return errors.New("accounts.SystemProgram is not set")
		}
		if inst.AccountMetaSlice[12] == nil {
			return errors.New("accounts.Rent is not set")
		}
	}
	return nil
}

func (inst *VrfLiteInit) EncodeToTree(parent ag_treeout.Branches) {
	parent.Child(ag_format.Program(ProgramName, ProgramID)).
		//
		ParentFunc(func(programBranch ag_treeout.Branches) {
			programBranch.Child(ag_format.Instruction("VrfLiteInit")).
				//
				ParentFunc(func(instructionBranch ag_treeout.Branches) {

					// Parameters of the instruction:
					instructionBranch.Child("Params[len=1]").ParentFunc(func(paramsBranch ag_treeout.Branches) {
						paramsBranch.Child(ag_format.Param("Params", *inst.Params))
					})

					// Accounts of the instruction:
					instructionBranch.Child("Accounts[len=13]").ParentFunc(func(accountsBranch ag_treeout.Branches) {
						accountsBranch.Child(ag_format.Meta("             authority", inst.AccountMetaSlice.Get(0)))
						accountsBranch.Child(ag_format.Meta("                   vrf", inst.AccountMetaSlice.Get(1)))
						accountsBranch.Child(ag_format.Meta("                  mint", inst.AccountMetaSlice.Get(2)))
						accountsBranch.Child(ag_format.Meta("                escrow", inst.AccountMetaSlice.Get(3)))
						accountsBranch.Child(ag_format.Meta("        queueAuthority", inst.AccountMetaSlice.Get(4)))
						accountsBranch.Child(ag_format.Meta("                 queue", inst.AccountMetaSlice.Get(5)))
						accountsBranch.Child(ag_format.Meta("            permission", inst.AccountMetaSlice.Get(6)))
						accountsBranch.Child(ag_format.Meta("          programState", inst.AccountMetaSlice.Get(7)))
						accountsBranch.Child(ag_format.Meta("                 payer", inst.AccountMetaSlice.Get(8)))
						accountsBranch.Child(ag_format.Meta("          tokenProgram", inst.AccountMetaSlice.Get(9)))
						accountsBranch.Child(ag_format.Meta("associatedTokenProgram", inst.AccountMetaSlice.Get(10)))
						accountsBranch.Child(ag_format.Meta("         systemProgram", inst.AccountMetaSlice.Get(11)))
						accountsBranch.Child(ag_format.Meta("                  rent", inst.AccountMetaSlice.Get(12)))
					})
				})
		})
}

func (obj VrfLiteInit) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	// Serialize `Params` param:
	err = encoder.Encode(obj.Params)
	if err != nil {
		return err
	}
	return nil
}
func (obj *VrfLiteInit) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	// Deserialize `Params`:
	err = decoder.Decode(&obj.Params)
	if err != nil {
		return err
	}
	return nil
}

// NewVrfLiteInitInstruction declares a new VrfLiteInit instruction with the provided parameters and accounts.
func NewVrfLiteInitInstruction(
	// Parameters:
	params VrfLiteInitParams,
	// Accounts:
	authority ag_solanago.PublicKey,
	vrf ag_solanago.PublicKey,
	mint ag_solanago.PublicKey,
	escrow ag_solanago.PublicKey,
	queueAuthority ag_solanago.PublicKey,
	queue ag_solanago.PublicKey,
	permission ag_solanago.PublicKey,
	programState ag_solanago.PublicKey,
	payer ag_solanago.PublicKey,
	tokenProgram ag_solanago.PublicKey,
	associatedTokenProgram ag_solanago.PublicKey,
	systemProgram ag_solanago.PublicKey,
	rent ag_solanago.PublicKey) *VrfLiteInit {
	return NewVrfLiteInitInstructionBuilder().
		SetParams(params).
		SetAuthorityAccount(authority).
		SetVrfAccount(vrf).
		SetMintAccount(mint).
		SetEscrowAccount(escrow).
		SetQueueAuthorityAccount(queueAuthority).
		SetQueueAccount(queue).
		SetPermissionAccount(permission).
		SetProgramStateAccount(programState).
		SetPayerAccount(payer).
		SetTokenProgramAccount(tokenProgram).
		SetAssociatedTokenProgramAccount(associatedTokenProgram).
		SetSystemProgramAccount(systemProgram).
		SetRentAccount(rent)
}
