// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.

package switchboard_v2

import (
	"errors"
	ag_binary "github.com/gagliardetto/binary"
	ag_solanago "github.com/gagliardetto/solana-go"
	ag_format "github.com/gagliardetto/solana-go/text/format"
	ag_treeout "github.com/gagliardetto/treeout"
)

// VrfLiteRequestRandomness is the `vrfLiteRequestRandomness` instruction.
type VrfLiteRequestRandomness struct {
	Params *VrfLiteRequestRandomnessParams

	// [0] = [SIGNER] authority
	//
	// [1] = [WRITE] vrfLite
	//
	// [2] = [WRITE] queue
	//
	// [3] = [] queueAuthority
	//
	// [4] = [] dataBuffer
	//
	// [5] = [WRITE] permission
	//
	// [6] = [WRITE] escrow
	//
	// [7] = [] recentBlockhashes
	//
	// [8] = [] programState
	//
	// [9] = [] tokenProgram
	ag_solanago.AccountMetaSlice `bin:"-"`
}

// NewVrfLiteRequestRandomnessInstructionBuilder creates a new `VrfLiteRequestRandomness` instruction builder.
func NewVrfLiteRequestRandomnessInstructionBuilder() *VrfLiteRequestRandomness {
	nd := &VrfLiteRequestRandomness{
		AccountMetaSlice: make(ag_solanago.AccountMetaSlice, 10),
	}
	return nd
}

// SetParams sets the "params" parameter.
func (inst *VrfLiteRequestRandomness) SetParams(params VrfLiteRequestRandomnessParams) *VrfLiteRequestRandomness {
	inst.Params = &params
	return inst
}

// SetAuthorityAccount sets the "authority" account.
func (inst *VrfLiteRequestRandomness) SetAuthorityAccount(authority ag_solanago.PublicKey) *VrfLiteRequestRandomness {
	inst.AccountMetaSlice[0] = ag_solanago.Meta(authority).SIGNER()
	return inst
}

// GetAuthorityAccount gets the "authority" account.
func (inst *VrfLiteRequestRandomness) GetAuthorityAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(0)
}

// SetVrfLiteAccount sets the "vrfLite" account.
func (inst *VrfLiteRequestRandomness) SetVrfLiteAccount(vrfLite ag_solanago.PublicKey) *VrfLiteRequestRandomness {
	inst.AccountMetaSlice[1] = ag_solanago.Meta(vrfLite).WRITE()
	return inst
}

// GetVrfLiteAccount gets the "vrfLite" account.
func (inst *VrfLiteRequestRandomness) GetVrfLiteAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(1)
}

// SetQueueAccount sets the "queue" account.
func (inst *VrfLiteRequestRandomness) SetQueueAccount(queue ag_solanago.PublicKey) *VrfLiteRequestRandomness {
	inst.AccountMetaSlice[2] = ag_solanago.Meta(queue).WRITE()
	return inst
}

// GetQueueAccount gets the "queue" account.
func (inst *VrfLiteRequestRandomness) GetQueueAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(2)
}

// SetQueueAuthorityAccount sets the "queueAuthority" account.
func (inst *VrfLiteRequestRandomness) SetQueueAuthorityAccount(queueAuthority ag_solanago.PublicKey) *VrfLiteRequestRandomness {
	inst.AccountMetaSlice[3] = ag_solanago.Meta(queueAuthority)
	return inst
}

// GetQueueAuthorityAccount gets the "queueAuthority" account.
func (inst *VrfLiteRequestRandomness) GetQueueAuthorityAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(3)
}

// SetDataBufferAccount sets the "dataBuffer" account.
func (inst *VrfLiteRequestRandomness) SetDataBufferAccount(dataBuffer ag_solanago.PublicKey) *VrfLiteRequestRandomness {
	inst.AccountMetaSlice[4] = ag_solanago.Meta(dataBuffer)
	return inst
}

// GetDataBufferAccount gets the "dataBuffer" account.
func (inst *VrfLiteRequestRandomness) GetDataBufferAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(4)
}

// SetPermissionAccount sets the "permission" account.
func (inst *VrfLiteRequestRandomness) SetPermissionAccount(permission ag_solanago.PublicKey) *VrfLiteRequestRandomness {
	inst.AccountMetaSlice[5] = ag_solanago.Meta(permission).WRITE()
	return inst
}

// GetPermissionAccount gets the "permission" account.
func (inst *VrfLiteRequestRandomness) GetPermissionAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(5)
}

// SetEscrowAccount sets the "escrow" account.
func (inst *VrfLiteRequestRandomness) SetEscrowAccount(escrow ag_solanago.PublicKey) *VrfLiteRequestRandomness {
	inst.AccountMetaSlice[6] = ag_solanago.Meta(escrow).WRITE()
	return inst
}

// GetEscrowAccount gets the "escrow" account.
func (inst *VrfLiteRequestRandomness) GetEscrowAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(6)
}

// SetRecentBlockhashesAccount sets the "recentBlockhashes" account.
func (inst *VrfLiteRequestRandomness) SetRecentBlockhashesAccount(recentBlockhashes ag_solanago.PublicKey) *VrfLiteRequestRandomness {
	inst.AccountMetaSlice[7] = ag_solanago.Meta(recentBlockhashes)
	return inst
}

// GetRecentBlockhashesAccount gets the "recentBlockhashes" account.
func (inst *VrfLiteRequestRandomness) GetRecentBlockhashesAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(7)
}

// SetProgramStateAccount sets the "programState" account.
func (inst *VrfLiteRequestRandomness) SetProgramStateAccount(programState ag_solanago.PublicKey) *VrfLiteRequestRandomness {
	inst.AccountMetaSlice[8] = ag_solanago.Meta(programState)
	return inst
}

// GetProgramStateAccount gets the "programState" account.
func (inst *VrfLiteRequestRandomness) GetProgramStateAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(8)
}

// SetTokenProgramAccount sets the "tokenProgram" account.
func (inst *VrfLiteRequestRandomness) SetTokenProgramAccount(tokenProgram ag_solanago.PublicKey) *VrfLiteRequestRandomness {
	inst.AccountMetaSlice[9] = ag_solanago.Meta(tokenProgram)
	return inst
}

// GetTokenProgramAccount gets the "tokenProgram" account.
func (inst *VrfLiteRequestRandomness) GetTokenProgramAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(9)
}

func (inst VrfLiteRequestRandomness) Build() *Instruction {
	return &Instruction{BaseVariant: ag_binary.BaseVariant{
		Impl:   inst,
		TypeID: Instruction_VrfLiteRequestRandomness,
	}}
}

// ValidateAndBuild validates the instruction parameters and accounts;
// if there is a validation error, it returns the error.
// Otherwise, it builds and returns the instruction.
func (inst VrfLiteRequestRandomness) ValidateAndBuild() (*Instruction, error) {
	if err := inst.Validate(); err != nil {
		return nil, err
	}
	return inst.Build(), nil
}

func (inst *VrfLiteRequestRandomness) Validate() error {
	// Check whether all (required) parameters are set:
	{
		if inst.Params == nil {
			return errors.New("Params parameter is not set")
		}
	}

	// Check whether all (required) accounts are set:
	{
		if inst.AccountMetaSlice[0] == nil {
			return errors.New("accounts.Authority is not set")
		}
		if inst.AccountMetaSlice[1] == nil {
			return errors.New("accounts.VrfLite is not set")
		}
		if inst.AccountMetaSlice[2] == nil {
			return errors.New("accounts.Queue is not set")
		}
		if inst.AccountMetaSlice[3] == nil {
			return errors.New("accounts.QueueAuthority is not set")
		}
		if inst.AccountMetaSlice[4] == nil {
			return errors.New("accounts.DataBuffer is not set")
		}
		if inst.AccountMetaSlice[5] == nil {
			return errors.New("accounts.Permission is not set")
		}
		if inst.AccountMetaSlice[6] == nil {
			return errors.New("accounts.Escrow is not set")
		}
		if inst.AccountMetaSlice[7] == nil {
			return errors.New("accounts.RecentBlockhashes is not set")
		}
		if inst.AccountMetaSlice[8] == nil {
			return errors.New("accounts.ProgramState is not set")
		}
		if inst.AccountMetaSlice[9] == nil {
			return errors.New("accounts.TokenProgram is not set")
		}
	}
	return nil
}

func (inst *VrfLiteRequestRandomness) EncodeToTree(parent ag_treeout.Branches) {
	parent.Child(ag_format.Program(ProgramName, ProgramID)).
		//
		ParentFunc(func(programBranch ag_treeout.Branches) {
			programBranch.Child(ag_format.Instruction("VrfLiteRequestRandomness")).
				//
				ParentFunc(func(instructionBranch ag_treeout.Branches) {

					// Parameters of the instruction:
					instructionBranch.Child("Params[len=1]").ParentFunc(func(paramsBranch ag_treeout.Branches) {
						paramsBranch.Child(ag_format.Param("Params", *inst.Params))
					})

					// Accounts of the instruction:
					instructionBranch.Child("Accounts[len=10]").ParentFunc(func(accountsBranch ag_treeout.Branches) {
						accountsBranch.Child(ag_format.Meta("        authority", inst.AccountMetaSlice.Get(0)))
						accountsBranch.Child(ag_format.Meta("          vrfLite", inst.AccountMetaSlice.Get(1)))
						accountsBranch.Child(ag_format.Meta("            queue", inst.AccountMetaSlice.Get(2)))
						accountsBranch.Child(ag_format.Meta("   queueAuthority", inst.AccountMetaSlice.Get(3)))
						accountsBranch.Child(ag_format.Meta("       dataBuffer", inst.AccountMetaSlice.Get(4)))
						accountsBranch.Child(ag_format.Meta("       permission", inst.AccountMetaSlice.Get(5)))
						accountsBranch.Child(ag_format.Meta("           escrow", inst.AccountMetaSlice.Get(6)))
						accountsBranch.Child(ag_format.Meta("recentBlockhashes", inst.AccountMetaSlice.Get(7)))
						accountsBranch.Child(ag_format.Meta("     programState", inst.AccountMetaSlice.Get(8)))
						accountsBranch.Child(ag_format.Meta("     tokenProgram", inst.AccountMetaSlice.Get(9)))
					})
				})
		})
}

func (obj VrfLiteRequestRandomness) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	// Serialize `Params` param:
	err = encoder.Encode(obj.Params)
	if err != nil {
		return err
	}
	return nil
}
func (obj *VrfLiteRequestRandomness) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	// Deserialize `Params`:
	err = decoder.Decode(&obj.Params)
	if err != nil {
		return err
	}
	return nil
}

// NewVrfLiteRequestRandomnessInstruction declares a new VrfLiteRequestRandomness instruction with the provided parameters and accounts.
func NewVrfLiteRequestRandomnessInstruction(
	// Parameters:
	params VrfLiteRequestRandomnessParams,
	// Accounts:
	authority ag_solanago.PublicKey,
	vrfLite ag_solanago.PublicKey,
	queue ag_solanago.PublicKey,
	queueAuthority ag_solanago.PublicKey,
	dataBuffer ag_solanago.PublicKey,
	permission ag_solanago.PublicKey,
	escrow ag_solanago.PublicKey,
	recentBlockhashes ag_solanago.PublicKey,
	programState ag_solanago.PublicKey,
	tokenProgram ag_solanago.PublicKey) *VrfLiteRequestRandomness {
	return NewVrfLiteRequestRandomnessInstructionBuilder().
		SetParams(params).
		SetAuthorityAccount(authority).
		SetVrfLiteAccount(vrfLite).
		SetQueueAccount(queue).
		SetQueueAuthorityAccount(queueAuthority).
		SetDataBufferAccount(dataBuffer).
		SetPermissionAccount(permission).
		SetEscrowAccount(escrow).
		SetRecentBlockhashesAccount(recentBlockhashes).
		SetProgramStateAccount(programState).
		SetTokenProgramAccount(tokenProgram)
}
