// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.

package switchboard_v2

import (
	"errors"
	ag_binary "github.com/gagliardetto/binary"
	ag_solanago "github.com/gagliardetto/solana-go"
	ag_format "github.com/gagliardetto/solana-go/text/format"
	ag_treeout "github.com/gagliardetto/treeout"
)

// VrfSetCallback is the `vrfSetCallback` instruction.
type VrfSetCallback struct {
	Params *VrfSetCallbackParams

	// [0] = [WRITE] vrf
	//
	// [1] = [SIGNER] authority
	ag_solanago.AccountMetaSlice `bin:"-"`
}

// NewVrfSetCallbackInstructionBuilder creates a new `VrfSetCallback` instruction builder.
func NewVrfSetCallbackInstructionBuilder() *VrfSetCallback {
	nd := &VrfSetCallback{
		AccountMetaSlice: make(ag_solanago.AccountMetaSlice, 2),
	}
	return nd
}

// SetParams sets the "params" parameter.
func (inst *VrfSetCallback) SetParams(params VrfSetCallbackParams) *VrfSetCallback {
	inst.Params = &params
	return inst
}

// SetVrfAccount sets the "vrf" account.
func (inst *VrfSetCallback) SetVrfAccount(vrf ag_solanago.PublicKey) *VrfSetCallback {
	inst.AccountMetaSlice[0] = ag_solanago.Meta(vrf).WRITE()
	return inst
}

// GetVrfAccount gets the "vrf" account.
func (inst *VrfSetCallback) GetVrfAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(0)
}

// SetAuthorityAccount sets the "authority" account.
func (inst *VrfSetCallback) SetAuthorityAccount(authority ag_solanago.PublicKey) *VrfSetCallback {
	inst.AccountMetaSlice[1] = ag_solanago.Meta(authority).SIGNER()
	return inst
}

// GetAuthorityAccount gets the "authority" account.
func (inst *VrfSetCallback) GetAuthorityAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(1)
}

func (inst VrfSetCallback) Build() *Instruction {
	return &Instruction{BaseVariant: ag_binary.BaseVariant{
		Impl:   inst,
		TypeID: Instruction_VrfSetCallback,
	}}
}

// ValidateAndBuild validates the instruction parameters and accounts;
// if there is a validation error, it returns the error.
// Otherwise, it builds and returns the instruction.
func (inst VrfSetCallback) ValidateAndBuild() (*Instruction, error) {
	if err := inst.Validate(); err != nil {
		return nil, err
	}
	return inst.Build(), nil
}

func (inst *VrfSetCallback) Validate() error {
	// Check whether all (required) parameters are set:
	{
		if inst.Params == nil {
			return errors.New("Params parameter is not set")
		}
	}

	// Check whether all (required) accounts are set:
	{
		if inst.AccountMetaSlice[0] == nil {
			return errors.New("accounts.Vrf is not set")
		}
		if inst.AccountMetaSlice[1] == nil {
			return errors.New("accounts.Authority is not set")
		}
	}
	return nil
}

func (inst *VrfSetCallback) EncodeToTree(parent ag_treeout.Branches) {
	parent.Child(ag_format.Program(ProgramName, ProgramID)).
		//
		ParentFunc(func(programBranch ag_treeout.Branches) {
			programBranch.Child(ag_format.Instruction("VrfSetCallback")).
				//
				ParentFunc(func(instructionBranch ag_treeout.Branches) {

					// Parameters of the instruction:
					instructionBranch.Child("Params[len=1]").ParentFunc(func(paramsBranch ag_treeout.Branches) {
						paramsBranch.Child(ag_format.Param("Params", *inst.Params))
					})

					// Accounts of the instruction:
					instructionBranch.Child("Accounts[len=2]").ParentFunc(func(accountsBranch ag_treeout.Branches) {
						accountsBranch.Child(ag_format.Meta("      vrf", inst.AccountMetaSlice.Get(0)))
						accountsBranch.Child(ag_format.Meta("authority", inst.AccountMetaSlice.Get(1)))
					})
				})
		})
}

func (obj VrfSetCallback) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	// Serialize `Params` param:
	err = encoder.Encode(obj.Params)
	if err != nil {
		return err
	}
	return nil
}
func (obj *VrfSetCallback) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	// Deserialize `Params`:
	err = decoder.Decode(&obj.Params)
	if err != nil {
		return err
	}
	return nil
}

// NewVrfSetCallbackInstruction declares a new VrfSetCallback instruction with the provided parameters and accounts.
func NewVrfSetCallbackInstruction(
	// Parameters:
	params VrfSetCallbackParams,
	// Accounts:
	vrf ag_solanago.PublicKey,
	authority ag_solanago.PublicKey) *VrfSetCallback {
	return NewVrfSetCallbackInstructionBuilder().
		SetParams(params).
		SetVrfAccount(vrf).
		SetAuthorityAccount(authority)
}
